from flask import Flask
from unittest.mock import patch

from blueprints.bp_stock import bp_stock


class _Rows:
    def __init__(self, rows=None):
        self._rows = rows or []

    def fetchall(self):
        return list(self._rows)


class _AvailableStockConnection:
    def __init__(self):
        self.queries = []

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def execute(self, query, params=()):
        self.queries.append(" ".join(str(query).split()))
        return _Rows(
            [
                {
                    "serial_number": "SER-LIBRE",
                    "component_type": "Procesador",
                    "brand_model": "AMD Ryzen",
                    "supplier": "Proveedor",
                    "is_autogenerated_id": 0,
                }
            ]
        )


def test_available_stock_query_excludes_assets_already_reserved_or_assigned():
    app = Flask(__name__)
    app.register_blueprint(bp_stock)
    connection = _AvailableStockConnection()

    with patch("blueprints.bp_stock.get_db_connection", return_value=connection), app.test_client() as client:
        response = client.get("/api/components/stock_available")

    assert response.status_code == 200
    query = connection.queries[0]
    assert "(lifecycle_status = 'stock' OR lifecycle_status IS NULL)" in query
    assert "(assigned_user IS NULL OR assigned_user = '')" in query
    assert "(assigned_fuero IS NULL OR assigned_fuero = '')" in query
    assert "(build_order_id IS NULL OR build_order_id = 0)" in query
