import unittest

from services.pc_details_service import _enrich_components_with_remitos, _filter_display_components_for_pc


class _EmptyResult:
    def fetchall(self):
        return []

    def fetchone(self):
        return None


class _FakeConn:
    def execute(self, _query, _params=None):
        return _EmptyResult()


class PcDetailComponentFilteringTests(unittest.TestCase):
    def test_hides_zero_gb_usb_reader_from_patimonial_display(self):
        components, _monitors = _filter_display_components_for_pc(
            components=[
                {
                    "id": 1,
                    "component_type": "Disco Rígido / SSD",
                    "brand_model": "Generic USB SD Reader USB Device (0GB)",
                    "serial_number": "058F63326330",
                    "assigned_pc": "SISTEMAS-105",
                },
                {
                    "id": 2,
                    "component_type": "Gabinete",
                    "brand_model": "PC de escritorio",
                    "serial_number": "PC-105",
                    "assigned_pc": "SISTEMAS-105",
                },
            ],
            monitors_detail=[],
            pc_name="SISTEMAS-105",
        )

        self.assertEqual([item["serial_number"] for item in components], ["PC-105"])

    def test_excludes_audit_only_component_that_was_returned_to_stock(self):
        components, monitors = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "H9TW800682",
                    "component_type": "Monitor",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Stock",
                    "assigned_pc": None,
                    "assigned_user": "Gustavo",
                    "assigned_fuero": "Desconocido",
                    "source": "audit",
                }
            ],
            monitors_detail=[
                {
                    "serial_number": "H9TW800682",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Stock",
                    "assigned_pc": None,
                    "assigned_user": "Gustavo",
                    "assigned_fuero": "Desconocido",
                    "source": "audit",
                }
            ],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(components, [])
        self.assertEqual(monitors, [])

    def test_keeps_installed_component_assigned_to_same_pc(self):
        components, monitors = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "SER-OK-1",
                    "component_type": "Monitor",
                    "brand_model": "Dell P2219H",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "assigned_user": "Gustavo",
                    "source": "stock",
                    "build_order_id": 6,
                }
            ],
            monitors_detail=[],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(len(components), 1)
        self.assertEqual(components[0]["serial_number"], "SER-OK-1")
        self.assertEqual(monitors, [])

    def test_keeps_audit_sourced_monitor_when_it_is_actively_assigned(self):
        components, monitors = _filter_display_components_for_pc(
            components=[],
            monitors_detail=[
                {
                    "serial_number": "H9TW800682",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "assigned_user": "Gustavo",
                    "assigned_fuero": "Desconocido",
                    "source": "audit",
                    "build_order_id": 6,
                }
            ],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(components, [])
        self.assertEqual(len(monitors), 1)
        self.assertEqual(monitors[0]["serial_number"], "H9TW800682")

    def test_excludes_component_owned_by_another_build_order(self):
        components, _ = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "SER-OLD-BO",
                    "component_type": "Teclado",
                    "brand_model": "Logitech",
                    "status": "Installed",
                    "assigned_pc": None,
                    "source": "stock",
                    "build_order_id": 99,
                }
            ],
            monitors_detail=[],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(components, [])

    def test_hides_autogenerated_shadow_when_real_component_same_family_and_model_exists(self):
        components, _ = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "DSK-NVME-512G-006",
                    "component_type": "Disco Rígido",
                    "brand_model": "NVMe Kingston 512GB M.2",
                    "status": "Installed",
                    "assigned_pc": "JCC1-PC01",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                },
                {
                    "serial_number": "INT-DIS-20260813-2795",
                    "component_type": "Disco Rígido / SSD",
                    "brand_model": "NVMe Kingston 512GB M.2",
                    "status": "Installed",
                    "assigned_pc": "JCC1-PC01",
                    "source": "stock",
                    "is_autogenerated_id": 1,
                },
            ],
            monitors_detail=[],
            pc_name="JCC1-PC01",
            linked_bo_id=4,
        )

        self.assertEqual(len(components), 1)
        self.assertEqual(components[0]["serial_number"], "DSK-NVME-512G-006")

    def test_keeps_multiple_real_monitors_even_if_same_model(self):
        _, monitors = _filter_display_components_for_pc(
            components=[],
            monitors_detail=[
                {
                    "serial_number": "MON-001",
                    "component_type": "Monitor",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                },
                {
                    "serial_number": "MON-002",
                    "component_type": "Monitor",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                },
            ],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(len(monitors), 2)

    def test_does_not_duplicate_registered_motherboard_with_audit_shadow(self):
        _monitors, components = _enrich_components_with_remitos(
            _FakeConn(),
            pc_components=[
                {
                    "id": 10,
                    "serial_number": "MB-OFICIAL-1",
                    "component_type": "Placa Madre",
                    "brand_model": "ASUS PRIME H510M-K",
                    "status": "Installed",
                    "assigned_pc": "TFSIIIV7000021",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                }
            ],
            hardware_components={
                "motherboard": {"model": "ASUS PRIME H510M-K", "serial": "To be filled by O.E.M."},
                "ram_modules": [],
                "disks": [],
                "monitors": [],
                "processor": "N/A",
            },
        )

        motherboards = [c for c in components if c["component_type"].lower() in {"placa madre", "motherboard"}]
        self.assertEqual(len(motherboards), 1)
        self.assertEqual(motherboards[0]["serial_number"], "MB-OFICIAL-1")

    def test_does_not_duplicate_single_registered_monitor_with_audit_shadow(self):
        monitors, components = _enrich_components_with_remitos(
            _FakeConn(),
            pc_components=[
                {
                    "id": 12,
                    "serial_number": "MON-OFICIAL-1",
                    "component_type": "Monitor",
                    "brand_model": "Samsung LS22",
                    "status": "Installed",
                    "assigned_pc": "TFSIIIV7000021",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                }
            ],
            hardware_components={
                "motherboard": {"model": "N/A", "serial": "N/A"},
                "ram_modules": [],
                "disks": [],
                "monitors": [{"model": "Monitor generico PnP", "serial": "AUDIT-MON-1"}],
                "processor": "N/A",
            },
        )

        monitor_components = [c for c in components if c["component_type"].lower() == "monitor"]
        self.assertEqual(len(monitors), 1)
        self.assertEqual(len(monitor_components), 1)
        self.assertEqual(monitors[0]["serial_number"], "MON-OFICIAL-1")

    def test_does_not_duplicate_single_registered_disk_with_audit_shadow(self):
        _monitors, components = _enrich_components_with_remitos(
            _FakeConn(),
            pc_components=[
                {
                    "id": 11,
                    "serial_number": "DSK-OFICIAL-1",
                    "component_type": "Disco Rígido / SSD",
                    "brand_model": "KINGSTON SA400S37240G",
                    "status": "Installed",
                    "assigned_pc": "TFSIIIV7000021",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                }
            ],
            hardware_components={
                "motherboard": {"model": "N/A", "serial": "N/A"},
                "ram_modules": [],
                "disks": [{"model": "KINGSTON SA400S37240G", "serial": "50026B7783ABCDEF"}],
                "monitors": [],
                "processor": "N/A",
            },
        )

        disks = [c for c in components if "DISCO" in c["component_type"].upper() or "SSD" in c["component_type"].upper()]
        self.assertEqual(len(disks), 1)
        self.assertEqual(disks[0]["serial_number"], "DSK-OFICIAL-1")


if __name__ == "__main__":
    unittest.main()
