import unittest
from unittest.mock import patch


class AutogeneratedDuplicateCleanupTests(unittest.TestCase):
    def test_detects_only_autogenerated_shadow_components(self):
        from services.pc_details_service import find_autogenerated_shadow_components

        candidates = find_autogenerated_shadow_components([
            {
                "serial_number": "DSK-REAL-001",
                "component_type": "Disco Rígido",
                "brand_model": "NVMe Kingston 512GB M.2",
                "is_autogenerated_id": 0,
            },
            {
                "serial_number": "INT-DIS-20260813-2795",
                "component_type": "Disco Rígido / SSD",
                "brand_model": "NVMe Kingston 512GB M.2",
                "is_autogenerated_id": 1,
            },
            {
                "serial_number": "MON-REAL-001",
                "component_type": "Monitor",
                "brand_model": "Samsung LS27C36x",
                "is_autogenerated_id": 0,
            },
            {
                "serial_number": "MON-REAL-002",
                "component_type": "Monitor",
                "brand_model": "Samsung LS27C36x",
                "is_autogenerated_id": 0,
            },
            {
                "serial_number": "INT-CPU-001",
                "component_type": "Procesador",
                "brand_model": "Intel Core i5-12400",
                "is_autogenerated_id": 1,
            },
        ])

        self.assertEqual(len(candidates), 1)
        self.assertEqual(candidates[0]["serial_number"], "INT-DIS-20260813-2795")
        self.assertEqual(candidates[0]["shadowed_by_serial_number"], "DSK-REAL-001")

    def test_detects_shadow_components_per_owner(self):
        from services.pc_details_service import find_autogenerated_shadow_components_by_owner

        candidates = find_autogenerated_shadow_components_by_owner([
            {
                "serial_number": "DSK-REAL-001",
                "component_type": "Disco Rígido",
                "brand_model": "NVMe Kingston 512GB M.2",
                "assigned_pc": "PC-1",
                "is_autogenerated_id": 0,
            },
            {
                "serial_number": "INT-DIS-001",
                "component_type": "Disco Rígido / SSD",
                "brand_model": "NVMe Kingston 512GB M.2",
                "assigned_pc": "PC-1",
                "is_autogenerated_id": 1,
            },
            {
                "serial_number": "INT-DIS-002",
                "component_type": "Disco Rígido / SSD",
                "brand_model": "NVMe Kingston 512GB M.2",
                "assigned_pc": "PC-2",
                "is_autogenerated_id": 1,
            },
        ])

        self.assertEqual(len(candidates), 1)
        self.assertEqual(candidates[0]["serial_number"], "INT-DIS-001")

    def test_ignored_autogenerated_shadow_component_is_not_reported(self):
        from services.pc_details_service import find_autogenerated_shadow_components_by_owner

        candidates = find_autogenerated_shadow_components_by_owner([
            {
                "serial_number": "DSK-REAL-001",
                "component_type": "Disco Rígido",
                "brand_model": "NVMe Kingston 512GB M.2",
                "assigned_pc": "PC-1",
                "is_autogenerated_id": 0,
                "ignore_autogenerated_duplicate": 0,
            },
            {
                "serial_number": "INT-DIS-001",
                "component_type": "Disco Rígido / SSD",
                "brand_model": "NVMe Kingston 512GB M.2",
                "assigned_pc": "PC-1",
                "is_autogenerated_id": 1,
                "ignore_autogenerated_duplicate": 1,
            },
        ])

        self.assertEqual(candidates, [])

    @patch("blueprints.bp_dashboard.get_db_connection")
    @patch("blueprints.bp_dashboard.get_pc_detail_context")
    def test_cleanup_endpoint_deletes_detected_shadow_components(self, mock_get_context, mock_get_db):
        from flask import Flask
        from blueprints.bp_dashboard import bp_dashboard

        app = Flask(__name__)
        app.secret_key = "test_secret"
        app.register_blueprint(bp_dashboard)

        mock_get_context.return_value = {
            "autogenerated_shadow_candidates": [
                {
                    "serial_number": "INT-DIS-20260813-2795",
                    "component_type": "Disco Rígido / SSD",
                    "brand_model": "NVMe Kingston 512GB M.2",
                }
            ]
        }

        executed = []
        mock_conn = mock_get_db.return_value.__enter__.return_value

        class MockResult:
            def __init__(self, rows=None, row=None):
                self._rows = rows or []
                self._row = row

            def fetchall(self):
                return self._rows

            def fetchone(self):
                return self._row

        def side_effect(query, params=None):
            executed.append((str(query), params))
            sql = str(query)
            if "FROM components" in sql and "serial_number IN" in sql:
                return MockResult(rows=[
                    {
                        "serial_number": "INT-DIS-20260813-2795",
                        "component_type": "Disco Rígido / SSD",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "JCC1-PC01",
                    }
                ])
            return MockResult()

        mock_conn.execute.side_effect = side_effect

        with app.test_client() as client:
            with client.session_transaction() as sess:
                sess["auth_user"] = {
                    "username": "administrador",
                    "display_name": "Administrador",
                    "permissions": {"funcionario": True, "manage_stock": True, "can_manage_stock": True},
                    "is_superuser": False,
                }

            response = client.post("/api/pc/JCC1-PC01/resolve_autogenerated_duplicates")

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertEqual(payload["status"], "success")
        self.assertEqual(payload["deleted_count"], 1)
        delete_queries = [sql for sql, _ in executed if "DELETE FROM components WHERE serial_number = %s" in sql]
        self.assertEqual(len(delete_queries), 1)

    @patch("blueprints.bp_stock.get_db_connection")
    def test_stock_cleanup_endpoint_deletes_requested_detected_candidates(self, mock_get_db):
        from flask import Flask
        from blueprints.bp_stock import bp_stock

        app = Flask(__name__, template_folder="../templates")
        app.secret_key = "test_secret"
        app.config["TESTING"] = True
        app.register_blueprint(bp_stock)

        executed = []
        mock_conn = mock_get_db.return_value.__enter__.return_value

        class MockResult:
            def __init__(self, rows=None):
                self._rows = rows or []

            def fetchall(self):
                return self._rows

        def side_effect(query, params=None):
            executed.append((str(query), params))
            sql = str(query)
            if "SELECT *" in sql and "FROM components" in sql:
                return MockResult(rows=[
                    {
                        "serial_number": "DSK-REAL-001",
                        "component_type": "Disco Rígido",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "assigned_user": None,
                        "assigned_fuero": None,
                        "build_order_id": None,
                        "is_autogenerated_id": 0,
                    },
                    {
                        "serial_number": "INT-DIS-001",
                        "component_type": "Disco Rígido / SSD",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "assigned_user": None,
                        "assigned_fuero": None,
                        "build_order_id": None,
                        "is_autogenerated_id": 1,
                    },
                ])
            return MockResult()

        mock_conn.execute.side_effect = side_effect

        with app.test_client() as client:
            with client.session_transaction() as sess:
                sess["auth_user"] = {
                    "username": "administrador",
                    "display_name": "Administrador",
                    "permissions": {"funcionario": True, "manage_stock": True, "can_manage_stock": True},
                    "is_superuser": False,
                }
                sess["csrf_token"] = "tok"

            response = client.post(
                "/api/components/resolve_autogenerated_duplicates",
                json={"serials": ["INT-DIS-001"]},
                headers={"X-CSRF-Token": "tok"},
            )

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertEqual(payload["deleted_count"], 1)
        self.assertEqual(payload["deleted_serials"], ["INT-DIS-001"])

    @patch("blueprints.bp_stock.get_db_connection")
    def test_stock_candidates_endpoint_returns_current_candidates(self, mock_get_db):
        from flask import Flask
        from blueprints.bp_stock import bp_stock

        app = Flask(__name__, template_folder="../templates")
        app.secret_key = "test_secret"
        app.config["TESTING"] = True
        app.register_blueprint(bp_stock)

        mock_conn = mock_get_db.return_value.__enter__.return_value

        class MockResult:
            def __init__(self, rows=None):
                self._rows = rows or []

            def fetchall(self):
                return self._rows

        def side_effect(query, params=None):
            sql = str(query)
            if "SELECT *" in sql and "FROM components" in sql:
                return MockResult(rows=[
                    {
                        "serial_number": "DSK-REAL-001",
                        "component_type": "Disco Rígido",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "assigned_user": None,
                        "assigned_fuero": None,
                        "build_order_id": None,
                        "is_autogenerated_id": 0,
                    },
                    {
                        "serial_number": "INT-DIS-001",
                        "component_type": "Disco Rígido / SSD",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "assigned_user": None,
                        "assigned_fuero": None,
                        "build_order_id": None,
                        "is_autogenerated_id": 1,
                    },
                ])
            return MockResult()

        mock_conn.execute.side_effect = side_effect

        with app.test_client() as client:
            with client.session_transaction() as sess:
                sess["auth_user"] = {
                    "username": "administrador",
                    "display_name": "Administrador",
                    "permissions": {"funcionario": True, "manage_stock": True, "can_manage_stock": True},
                    "is_superuser": False,
                }

            response = client.get("/api/components/autogenerated_duplicates")

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertEqual(payload["status"], "success")
        self.assertEqual(payload["count"], 1)
        self.assertEqual(payload["candidates"][0]["serial_number"], "INT-DIS-001")

    @patch("blueprints.bp_stock.get_db_connection")
    def test_ignore_endpoint_marks_requested_candidate_as_ignored(self, mock_get_db):
        from flask import Flask
        from blueprints.bp_stock import bp_stock

        app = Flask(__name__, template_folder="../templates")
        app.secret_key = "test_secret"
        app.config["TESTING"] = True
        app.register_blueprint(bp_stock)

        executed = []
        mock_conn = mock_get_db.return_value.__enter__.return_value

        class MockResult:
            def __init__(self, rows=None):
                self._rows = rows or []

            def fetchall(self):
                return self._rows

        def side_effect(query, params=None):
            executed.append((str(query), params))
            sql = str(query)
            if "SELECT *" in sql and "FROM components" in sql:
                return MockResult(rows=[
                    {
                        "serial_number": "DSK-REAL-001",
                        "component_type": "Disco Rígido",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "assigned_user": None,
                        "assigned_fuero": None,
                        "build_order_id": None,
                        "is_autogenerated_id": 0,
                        "ignore_autogenerated_duplicate": 0,
                    },
                    {
                        "serial_number": "INT-DIS-001",
                        "component_type": "Disco Rígido / SSD",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "assigned_user": None,
                        "assigned_fuero": None,
                        "build_order_id": None,
                        "is_autogenerated_id": 1,
                        "ignore_autogenerated_duplicate": 0,
                    },
                ])
            return MockResult()

        mock_conn.execute.side_effect = side_effect

        with app.test_client() as client:
            with client.session_transaction() as sess:
                sess["auth_user"] = {
                    "username": "administrador",
                    "display_name": "Administrador",
                    "permissions": {"funcionario": True, "manage_stock": True, "can_manage_stock": True},
                    "is_superuser": False,
                }
                sess["csrf_token"] = "tok"

            response = client.post(
                "/api/components/ignore_autogenerated_duplicates",
                json={"serials": ["INT-DIS-001"]},
                headers={"X-CSRF-Token": "tok"},
            )

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertEqual(payload["ignored_count"], 1)
        update_queries = [
            sql for sql, _ in executed
            if "UPDATE components" in sql
            and "ignore_autogenerated_duplicate = 1" in sql
            and "ignored_autogenerated_by = %s" in sql
            and "ignored_autogenerated_at = NOW()" in sql
        ]
        self.assertEqual(len(update_queries), 1)

    @patch("blueprints.bp_stock.get_db_connection")
    def test_ignored_candidates_endpoint_returns_ignored_auto_ids(self, mock_get_db):
        from flask import Flask
        from blueprints.bp_stock import bp_stock

        app = Flask(__name__, template_folder="../templates")
        app.secret_key = "test_secret"
        app.config["TESTING"] = True
        app.register_blueprint(bp_stock)

        mock_conn = mock_get_db.return_value.__enter__.return_value

        class MockResult:
            def __init__(self, rows=None):
                self._rows = rows or []

            def fetchall(self):
                return self._rows

        def side_effect(query, params=None):
            sql = str(query)
            if "ignore_autogenerated_duplicate = 1" in sql:
                return MockResult(rows=[
                    {
                        "serial_number": "INT-DIS-IGN-001",
                        "component_type": "Disco Rígido / SSD",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "assigned_user": None,
                        "assigned_fuero": None,
                        "build_order_id": None,
                        "ignore_autogenerated_duplicate": 1,
                        "ignored_autogenerated_by": "administrador",
                        "ignored_autogenerated_at": "2026-08-14 10:30:00",
                    }
                ])
            return MockResult()

        mock_conn.execute.side_effect = side_effect

        with app.test_client() as client:
            with client.session_transaction() as sess:
                sess["auth_user"] = {
                    "username": "administrador",
                    "display_name": "Administrador",
                    "permissions": {"funcionario": True, "manage_stock": True, "can_manage_stock": True},
                    "is_superuser": False,
                }

            response = client.get("/api/components/autogenerated_duplicates/ignored")

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertEqual(payload["status"], "success")
        self.assertEqual(payload["count"], 1)
        self.assertEqual(payload["components"][0]["serial_number"], "INT-DIS-IGN-001")
        self.assertEqual(payload["components"][0]["ignored_autogenerated_by"], "administrador")

    @patch("blueprints.bp_stock.get_db_connection")
    def test_unignore_endpoint_clears_ignore_flag(self, mock_get_db):
        from flask import Flask
        from blueprints.bp_stock import bp_stock

        app = Flask(__name__, template_folder="../templates")
        app.secret_key = "test_secret"
        app.config["TESTING"] = True
        app.register_blueprint(bp_stock)

        executed = []
        mock_conn = mock_get_db.return_value.__enter__.return_value

        class MockResult:
            def __init__(self, rows=None):
                self._rows = rows or []

            def fetchall(self):
                return self._rows

        def side_effect(query, params=None):
            executed.append((str(query), params))
            sql = str(query)
            if "ignore_autogenerated_duplicate = 1" in sql:
                return MockResult(rows=[
                    {
                        "serial_number": "INT-DIS-IGN-001",
                        "component_type": "Disco Rígido / SSD",
                        "brand_model": "NVMe Kingston 512GB M.2",
                        "assigned_pc": "PC-1",
                        "ignore_autogenerated_duplicate": 1,
                        "ignored_autogenerated_by": "administrador",
                        "ignored_autogenerated_at": "2026-08-14 10:30:00",
                    }
                ])
            return MockResult()

        mock_conn.execute.side_effect = side_effect

        with app.test_client() as client:
            with client.session_transaction() as sess:
                sess["auth_user"] = {
                    "username": "administrador",
                    "display_name": "Administrador",
                    "permissions": {"funcionario": True, "manage_stock": True, "can_manage_stock": True},
                    "is_superuser": False,
                }
                sess["csrf_token"] = "tok"

            response = client.post(
                "/api/components/unignore_autogenerated_duplicates",
                json={"serials": ["INT-DIS-IGN-001"]},
                headers={"X-CSRF-Token": "tok"},
            )

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertEqual(payload["restored_count"], 1)
        update_queries = [
            sql for sql, _ in executed
            if "UPDATE components" in sql
            and "ignore_autogenerated_duplicate = 0" in sql
            and "ignored_autogenerated_by = NULL" in sql
            and "ignored_autogenerated_at = NULL" in sql
        ]
        self.assertEqual(len(update_queries), 1)


if __name__ == "__main__":
    unittest.main()
