import unittest

from services.pc_details_service import _filter_display_components_for_pc


class PcDetailComponentFilteringTests(unittest.TestCase):
    def test_excludes_audit_only_component_that_was_returned_to_stock(self):
        components, monitors = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "H9TW800682",
                    "component_type": "Monitor",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Stock",
                    "assigned_pc": None,
                    "assigned_user": "Gustavo",
                    "assigned_fuero": "Desconocido",
                    "source": "audit",
                }
            ],
            monitors_detail=[
                {
                    "serial_number": "H9TW800682",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Stock",
                    "assigned_pc": None,
                    "assigned_user": "Gustavo",
                    "assigned_fuero": "Desconocido",
                    "source": "audit",
                }
            ],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(components, [])
        self.assertEqual(monitors, [])

    def test_keeps_installed_component_assigned_to_same_pc(self):
        components, monitors = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "SER-OK-1",
                    "component_type": "Monitor",
                    "brand_model": "Dell P2219H",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "assigned_user": "Gustavo",
                    "source": "stock",
                    "build_order_id": 6,
                }
            ],
            monitors_detail=[],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(len(components), 1)
        self.assertEqual(components[0]["serial_number"], "SER-OK-1")
        self.assertEqual(monitors, [])

    def test_keeps_audit_sourced_monitor_when_it_is_actively_assigned(self):
        components, monitors = _filter_display_components_for_pc(
            components=[],
            monitors_detail=[
                {
                    "serial_number": "H9TW800682",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "assigned_user": "Gustavo",
                    "assigned_fuero": "Desconocido",
                    "source": "audit",
                    "build_order_id": 6,
                }
            ],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(components, [])
        self.assertEqual(len(monitors), 1)
        self.assertEqual(monitors[0]["serial_number"], "H9TW800682")

    def test_excludes_component_owned_by_another_build_order(self):
        components, _ = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "SER-OLD-BO",
                    "component_type": "Teclado",
                    "brand_model": "Logitech",
                    "status": "Installed",
                    "assigned_pc": None,
                    "source": "stock",
                    "build_order_id": 99,
                }
            ],
            monitors_detail=[],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(components, [])

    def test_hides_autogenerated_shadow_when_real_component_same_family_and_model_exists(self):
        components, _ = _filter_display_components_for_pc(
            components=[
                {
                    "serial_number": "DSK-NVME-512G-006",
                    "component_type": "Disco Rígido",
                    "brand_model": "NVMe Kingston 512GB M.2",
                    "status": "Installed",
                    "assigned_pc": "JCC1-PC01",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                },
                {
                    "serial_number": "INT-DIS-20260813-2795",
                    "component_type": "Disco Rígido / SSD",
                    "brand_model": "NVMe Kingston 512GB M.2",
                    "status": "Installed",
                    "assigned_pc": "JCC1-PC01",
                    "source": "stock",
                    "is_autogenerated_id": 1,
                },
            ],
            monitors_detail=[],
            pc_name="JCC1-PC01",
            linked_bo_id=4,
        )

        self.assertEqual(len(components), 1)
        self.assertEqual(components[0]["serial_number"], "DSK-NVME-512G-006")

    def test_keeps_multiple_real_monitors_even_if_same_model(self):
        _, monitors = _filter_display_components_for_pc(
            components=[],
            monitors_detail=[
                {
                    "serial_number": "MON-001",
                    "component_type": "Monitor",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                },
                {
                    "serial_number": "MON-002",
                    "component_type": "Monitor",
                    "brand_model": "Samsung LS27C36x",
                    "status": "Installed",
                    "assigned_pc": "DESKTOP-BVVVOGR",
                    "source": "stock",
                    "is_autogenerated_id": 0,
                },
            ],
            pc_name="DESKTOP-BVVVOGR",
            linked_bo_id=6,
        )

        self.assertEqual(len(monitors), 2)


if __name__ == "__main__":
    unittest.main()
