CREATE TABLE equipos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL,
  ultimo_usuario VARCHAR(120) NULL,
  fuero VARCHAR(120) NOT NULL,
  ip VARCHAR(45) NULL,
  sistema_operativo VARCHAR(180) NULL,
  procesador VARCHAR(255) NULL,
  ram_mb INT NULL,
  impresora VARCHAR(180) NULL,
  monitoreo VARCHAR(60) NOT NULL DEFAULT 'SIN_REPORTE',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  ultimo_reporte_en TIMESTAMP NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_equipos_nombre UNIQUE (nombre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
