"""
asset_validation.py — Servicio de validación del Gemelo Digital Patrimonial.

Lógica central del Sistema Patrimonial:
  - Dado un pc_name, determina si la PC reportada por el script .ps1
    tiene un activo registrado en components y si el hardware coincide.

Valores de validation_status:
  'sin_gemelo'   → El script reportó esta PC pero no hay componente CPU asignado.
  'pendiente'    → Se asignó un CPU (Build Order o asignación directa) pero el script
                   no ha reportado desde esa asignación (last_report vacío o None).
  'validado'     → El hardware reportado coincide con el activo registrado.
  'discrepancia' → El hardware cambió respecto al activo registrado (posible
                   reemplazo sin documentar).

Este módulo NO modifica la tabla pcs; solo calcula el estado.
La escritura la hace el caller (bp_api.py → process_inventory_data).
"""

import logging
import re

logger = logging.getLogger(__name__)

_IGNORED_STORAGE_TOKENS = (
    "USB SD READER", "USB MS READER", "USB SM READER", "USB CF READER",
    "CARD READER USB DEVICE", "GENERIC USB STORAGE", "USB CR READER",
    "SD/MMC CARD READER", "USB DEVICE", "USB FLASH", "PENDRIVE",
    "DATATRAVELER", "CRUZER", "CARD READER", "CARD_READER",
    "MS READER", "SD READER", "CF READER", "SM READER", "SD/MMC CARD",
)


def is_ignored_storage_device(value: str) -> bool:
    """Indica si WMI describió un lector/medio USB que no es disco patrimonial."""
    normalized = str(value or "").upper()
    if not normalized:
        return False
    if any(marker in normalized for marker in ("(0GB)", "(0.00GB)", "0.0 GB", " 0GB")):
        return True
    return any(token in normalized for token in _IGNORED_STORAGE_TOKENS)


def is_ignored_storage_component(component) -> bool:
    """Aplica la exclusión solo a componentes que representan almacenamiento."""
    if not component:
        return False
    component_type = str(component.get("component_type") or "").upper()
    is_storage = any(token in component_type for token in ("DISCO", "SSD", "HDD", "ALMACEN"))
    return is_storage and is_ignored_storage_device(component.get("brand_model"))

# ─────────────────────────────────────────────────────────────────────────────
# Helpers de normalización (locales para evitar importar bp_api)
# ─────────────────────────────────────────────────────────────────────────────

def _normalize_hw_token(value: str) -> str:
    """Limpia un string de hardware para comparación tolerante a cambios menores."""
    if not value:
        return ""
    v = value.strip().upper()
    # Eliminar sufijos de velocidad / revisiones que no identifican el modelo
    v = re.sub(r"\s*@\s*[\d.]+\s*GHZ", "", v)
    v = re.sub(r"\s+REV\s*[\d.]+", "", v)
    # Eliminar prefijos de número de serie habituales como SN:, S/N:, UUID:
    v = re.sub(r"\[?\b(SN|S/N|SERIAL|UUID)\b\s*:\s*", "", v)
    # Reemplazar corchetes, paréntesis, comas y barras por espacios para evitar fallos por puntuación
    v = re.sub(r"[\[\]\(\)\,\;\|]", " ", v)
    v = re.sub(r"\s+", " ", v)
    return v.strip()


def _normalize_hw_identity(value: str) -> str:
    """Normaliza modelo para detectar filas sombra aunque difieran S/N o capacidad."""
    v = str(value or "").strip().upper()
    if not v:
        return ""
    v = re.sub(r"[\[\(]\s*(SN|S/N|SERIAL|UUID)\s*:\s*[^\]\)]+[\]\)]", " ", v)
    v = re.sub(r"\bSN\s*:\s*\S+", " ", v)
    v = re.sub(r"\(\s*\d+(?:\.\d+)?\s*GB\s*\)", " ", v)
    v = re.sub(r"\b\d+(?:\.\d+)?\s*GB\b", " ", v)
    v = _normalize_hw_token(v)
    return v


def _is_autogenerated_component(component) -> bool:
    serial = str(component.get("serial_number") or "").strip().upper()
    return bool(component.get("is_autogenerated_id")) or serial.startswith("INT-")


def _component_identity_key(component):
    return _normalize_hw_identity(component.get("brand_model"))


def _dedupe_validation_components(components):
    """Oculta componentes INT-* sombra antes de armar la comparación patrimonial."""
    result = []
    for component in components or []:
        current = dict(component)
        current_family = _normalize_component_type(current.get("component_type"))
        current_identity = _component_identity_key(current)
        if not current_identity:
            result.append(current)
            continue

        shadowed = False
        for idx, existing in enumerate(result):
            existing_family = _normalize_component_type(existing.get("component_type"))
            if existing_family != current_family:
                continue
            existing_identity = _component_identity_key(existing)
            equivalent = (
                existing_identity
                and (
                    existing_identity == current_identity
                    or existing_identity in current_identity
                    or current_identity in existing_identity
                )
            )
            if not equivalent:
                continue
            existing_auto = _is_autogenerated_component(existing)
            current_auto = _is_autogenerated_component(current)
            if existing_auto and not current_auto:
                result[idx] = current
            shadowed = True
            break

        if not shadowed:
            result.append(current)
    return result


def filter_ignore_devices(disk_str: str) -> str:
    """
    Filtra lectores de tarjetas USB (0GB, SD/MS/CF readers) de la cadena de discos
    para evitar falsas discrepancias en la auditoría del gemelo digital.
    """
    if not disk_str or disk_str == "Sin reporte de script":
        return disk_str or ""
    
    parts = [p.strip() for p in str(disk_str).split("|") if p.strip()]
    cleaned = []
    
    for p in parts:
        if is_ignored_storage_device(p):
            continue
        cleaned.append(p)
        
    return " | ".join(cleaned)


def _hw_tokens_match(a: str, b: str) -> bool:
    """Compara dos strings de hardware normalizados."""
    na, nb = _normalize_hw_token(a), _normalize_hw_token(b)
    if not na or not nb:
        return False
    # Coincidencia exacta o una como substring de la otra (cubre modelos abreviados)
    return na == nb or na in nb or nb in na


def _normalize_component_type(component_type: str) -> str:
    return (component_type or "").strip().lower()


def _extract_ram_total_gb(components, fallback_ram=None) -> float:
    total_stock_gb = 0.0
    for component in components:
        raw_value = f"{component.get('brand_model') or ''} {component.get('component_type') or ''}"
        match = re.search(r"(\d+(?:\.\d+)?)\s*GB", raw_value, re.IGNORECASE)
        if match:
            total_stock_gb += float(match.group(1))
    if total_stock_gb > 0:
        return total_stock_gb
    try:
        return float(fallback_ram or 0)
    except (TypeError, ValueError):
        return 0.0


def _extract_telemetry_ram_gb(script_ram) -> float:
    match = re.search(r"[\d.]+", str(script_ram or ""))
    return float(match.group()) if match else 0.0


def _ram_matches(components, script_ram, fallback_ram=None) -> bool:
    total_stock_gb = _extract_ram_total_gb(components, fallback_ram=fallback_ram)
    telem_gb = _extract_telemetry_ram_gb(script_ram)
    if total_stock_gb <= 0 or telem_gb <= 0:
        return False

    diff = abs(total_stock_gb - telem_gb)
    if diff <= 2.25 or round(telem_gb) == round(total_stock_gb) or int(round(telem_gb)) == int(total_stock_gb):
        return True

    for tier in [2, 4, 8, 16, 32, 64, 128]:
        if telem_gb <= tier and (tier - telem_gb) <= (tier * 0.35) and total_stock_gb == tier:
            return True
    return False


def _split_hardware_entries(raw_value: str):
    return [part.strip() for part in str(raw_value or "").split("|") if part.strip()]


def _storage_matches(components, script_disks, fallback_disks=None) -> bool:
    registered_entries = []
    if components:
        registered_entries = [str(component.get("brand_model") or "").strip() for component in components if str(component.get("brand_model") or "").strip()]
    elif fallback_disks:
        registered_entries = _split_hardware_entries(filter_ignore_devices(fallback_disks))

    telemetry_entries = _split_hardware_entries(filter_ignore_devices(script_disks))
    if not registered_entries or not telemetry_entries:
        return False

    return (
        all(any(_hw_tokens_match(reg_entry, telemetry_entry) for telemetry_entry in telemetry_entries) for reg_entry in registered_entries)
        and all(any(_hw_tokens_match(telemetry_entry, reg_entry) for reg_entry in registered_entries) for telemetry_entry in telemetry_entries)
    )


def resolve_effective_validation_status(
    validation_status: str,
    has_official_components=False,
    has_discrepancies=False,
) -> str:
    """Corrige para la vista un `sin_gemelo` obsoleto usando patrimonio real."""
    normalized = (validation_status or "sin_gemelo").strip().lower()
    if normalized == "sin_gemelo" and has_official_components:
        return "discrepancia" if has_discrepancies else "validado"
    return normalized


def resolve_build_order_action(
    validation_status: str,
    linked_bo=None,
    has_discrepancies=False,
    has_official_components=False,
) -> str:
    """Decide la acción patrimonial sin crear órdenes duplicadas.

    Un equipo que ya tiene gemelo conserva su historia aunque no se haya podido
    localizar una orden antigua. Una orden nueva solo corresponde a un equipo
    realmente sin gemelo. Si ya existe una orden, las diferencias se agregan a
    esa misma orden.
    """
    if linked_bo:
        return "update" if has_discrepancies else "history"
    return "create"


# ─────────────────────────────────────────────────────────────────────────────
# Función principal
# ─────────────────────────────────────────────────────────────────────────────

def compute_validation_status(pc_name: str, conn) -> str:
    """
    Calcula el validation_status de una PC dado su nombre y una conexión activa.

    Se llama al final de process_inventory_data() en bp_api.py, con la misma
    conexión abierta del UPSERT, para garantizar que los datos ya están escritos.

    Parámetros:
        pc_name : Nombre de la PC (clave primaria en pcs).
        conn    : Conexión activa (DBConnectionWrapper) — ya dentro de un contexto with.

    Retorna:
        str : 'sin_gemelo' | 'pendiente' | 'validado' | 'discrepancia'
    """
    try:
        # 1. ¿Hay algún activo patrimonial asignado a esta PC (en components o build_orders)?
        assigned_components = conn.execute(
            """
            SELECT id, component_type, brand_model, serial_number
            FROM components
            WHERE LOWER(TRIM(assigned_pc)) = LOWER(TRIM(%s))
              AND status NOT IN ('Retirado', 'Scrap')
              AND (lifecycle_status IS NULL OR lifecycle_status NOT IN ('retirado', 'scrap'))
            """,
            (pc_name,)
        ).fetchall()
        assigned_components = [component for component in assigned_components if not is_ignored_storage_component(component)]

        if not assigned_components:
            assigned_bo = conn.execute(
                """
                SELECT boi.id
                FROM build_order_items boi
                JOIN build_orders bo ON bo.id = boi.build_order_id
                WHERE LOWER(TRIM(boi.pc_name)) = LOWER(TRIM(%s))
                   OR LOWER(TRIM(bo.target_pc_name)) = LOWER(TRIM(%s))
                LIMIT 1
                """,
                (pc_name, pc_name)
            ).fetchone()
            if not assigned_bo:
                return "sin_gemelo"

        # 2. ¿La PC ya reportó desde el script?
        pc_data = conn.execute(
            "SELECT processor, motherboard_model, ram_gb, disk_models, last_report, telemetry_snapshot, full_json_data, validation_status FROM pcs WHERE pc_name = %s",
            (pc_name,)
        ).fetchone()

        if not pc_data or not pc_data.get("last_report"):
            # Activo asignado pero el script no corrió aún
                return "pendiente"

        # 3. Obtener telemetría del script desde telemetry_snapshot o full_json_data
        telemetry_raw = pc_data.get("telemetry_snapshot") or pc_data.get("full_json_data")
        script_processor = pc_data.get("processor") or ""
        script_motherboard = pc_data.get("motherboard_model") or ""
        script_ram = pc_data.get("ram_gb") or 0.0
        script_disks = pc_data.get("disk_models") or ""

        if telemetry_raw:
            try:
                import json
                t_data = json.loads(telemetry_raw)
                sistema = t_data.get("Sistema", {})
                script_processor = sistema.get("Procesador") or script_processor
                script_ram = sistema.get("RAM (GB)") or script_ram
                script_disks = t_data.get("Disk_Models") or script_disks
                script_motherboard = t_data.get("Motherboard_Model") or script_motherboard
            except Exception:
                pass

        # 4. Comparar contra el set patrimonial relevante, no contra una sola fila.
        comp_by_type = {}
        for component in assigned_components:
            comp_by_type.setdefault(_normalize_component_type(component.get("component_type")), []).append(component)

        cpu_comps = comp_by_type.get("procesador", []) + comp_by_type.get("microprocesador", []) + comp_by_type.get("cpu", []) + comp_by_type.get("micro", [])
        if script_processor and script_processor not in ("N/A", "") and cpu_comps:
            if not all(_hw_tokens_match(component.get("brand_model"), script_processor) for component in cpu_comps):
                return "discrepancia"

        mb_comps = comp_by_type.get("motherboard", []) + comp_by_type.get("placa madre", []) + comp_by_type.get("mother", []) + comp_by_type.get("placa", [])
        if script_motherboard and script_motherboard not in ("N/A", "") and mb_comps:
            if not all(_hw_tokens_match(component.get("brand_model"), script_motherboard) for component in mb_comps):
                return "discrepancia"

        ram_comps = comp_by_type.get("memoria ram", []) + comp_by_type.get("ram", []) + comp_by_type.get("memoria", [])
        if ram_comps:
            if not _ram_matches(ram_comps, script_ram, fallback_ram=None):
                return "discrepancia"
        else:
            reg_ram = pc_data.get("ram_gb")
            if reg_ram and float(reg_ram) > 0 and script_ram and float(script_ram) > 0:
                if not _ram_matches([], script_ram, fallback_ram=reg_ram):
                    return "discrepancia"

        disk_comps = (
            comp_by_type.get("disco rígido", [])
            + comp_by_type.get("disco rigido", [])
            + comp_by_type.get("disco ssd", [])
            + comp_by_type.get("ssd", [])
            + comp_by_type.get("disco", [])
            + comp_by_type.get("almacenamiento", [])
            + comp_by_type.get("disco rígido / ssd", [])
            + comp_by_type.get("disco rigido / ssd", [])
        )
        if script_disks and script_disks not in ("Sin reporte de script", "N/A"):
            if disk_comps:
                if not _storage_matches(disk_comps, script_disks):
                    return "discrepancia"
            else:
                fallback_disks = pc_data.get("disk_models")
                if fallback_disks and not _storage_matches([], script_disks, fallback_disks=fallback_disks):
                    return "discrepancia"

        return "validado"

    except Exception as exc:
        logger.warning(
            "compute_validation_status(%s): error calculando estado — %s",
            pc_name, exc
        )
        # Un fallo transitorio no debe borrar una validación patrimonial ya
        # confirmada. Recuperamos el estado persistido y solo usamos sin_gemelo
        # cuando tampoco puede consultarse.
        try:
            row = conn.execute(
                "SELECT validation_status FROM pcs WHERE pc_name = %s",
                (pc_name,),
            ).fetchone()
            previous = (row or {}).get("validation_status")
            if previous in {"sin_gemelo", "pendiente", "validado", "discrepancia"}:
                return previous
        except Exception:
            pass
        return "sin_gemelo"


# ─────────────────────────────────────────────────────────────────────────────
# Bulk recalculation (para usar desde panel de administración)
# ─────────────────────────────────────────────────────────────────────────────

def recalculate_all_validation_statuses() -> dict:
    """
    Recalcula el validation_status de TODAS las PCs activas.
    Se puede llamar desde un endpoint de administración para una pasada inicial
    después de la migración V49.

    Retorna un dict con conteos por estado para mostrar en la respuesta.
    """
    from database.db_core import get_db_connection

    counts = {"sin_gemelo": 0, "pendiente": 0, "validado": 0, "discrepancia": 0, "error": 0}

    try:
        with get_db_connection() as conn:
            pcs = conn.execute(
                "SELECT pc_name FROM pcs WHERE is_active = 1"
            ).fetchall()

            for row in pcs:
                pc_name = row["pc_name"]
                status = compute_validation_status(pc_name, conn)
                try:
                    conn.execute(
                        "UPDATE pcs SET validation_status = %s WHERE pc_name = %s",
                        (status, pc_name)
                    )
                    counts[status] = counts.get(status, 0) + 1
                except Exception as upd_exc:
                    logger.warning("Error actualizando validation_status para %s: %s", pc_name, upd_exc)
                    counts["error"] += 1

    except Exception as exc:
        logger.error("recalculate_all_validation_statuses: error general — %s", exc)

    logger.info("Recálculo validation_status completado: %s", counts)
    return counts


def get_pc_validation_comparison(pc_name: str, conn=None, unified_components=None):
    """
    Construye una comparativa estructurada entre el Armado Patrimonial (componentes asignados)
    y la Telemetría Real reportada por el script .ps1.
    """
    close_conn = False
    if conn is None:
        from database.db_core import get_db_connection
        conn_ctx = get_db_connection()
        conn = conn_ctx.__enter__()
        close_conn = True

    try:
        pc = conn.execute("SELECT * FROM pcs WHERE pc_name = %s", (pc_name,)).fetchone()
        if not pc:
            return []

        if unified_components is not None:
            comps = unified_components
        else:
            comps = conn.execute(
                "SELECT serial_number, component_type, brand_model FROM components WHERE LOWER(TRIM(assigned_pc)) = LOWER(TRIM(%s)) AND status NOT IN ('Retirado', 'Scrap')",
                (pc_name,)
            ).fetchall()

        comps = _dedupe_validation_components([c for c in comps if not is_ignored_storage_component(c)])
        has_twin_evidence = bool(comps)

        telemetry_raw = pc.get("telemetry_snapshot") or pc.get("full_json_data")
        script_data = {}
        if telemetry_raw:
            try:
                import json
                script_data = json.loads(telemetry_raw)
            except Exception:
                pass

        sistema = script_data.get("Sistema", {})
        script_proc = sistema.get("Procesador") or pc.get("processor") or "Sin reporte de script"
        script_ram = str(sistema.get("RAM (GB)") or pc.get("ram_gb") or "Sin reporte")
        script_mb = script_data.get("Motherboard_Model") or pc.get("motherboard_model") or "Sin reporte de script"
        raw_disk_str = script_data.get("Disk_Models") or pc.get("disk_models") or "Sin reporte de script"
        script_disk = filter_ignore_devices(raw_disk_str)

        comp_by_type = {}
        for c in comps:
            ctype = (c.get("component_type") or "Otro").strip().lower()
            comp_by_type.setdefault(ctype, []).append(c)

        comparison = []

        # 1. Motherboard
        mb_comps = comp_by_type.get("motherboard", []) + comp_by_type.get("placa madre", []) + comp_by_type.get("mother", []) + comp_by_type.get("placa", [])
        fallback_mb = pc.get("motherboard_model") if has_twin_evidence else None
        reg_mb = ", ".join(f"{c['brand_model']} ({c['serial_number'] or 'Sin S/N'})" for c in mb_comps) if mb_comps else (fallback_mb or "Sin registro en Stock")
        mb_has_reg = bool(mb_comps or fallback_mb)
        mb_has_telem = bool(script_mb and script_mb not in ("Sin reporte de script", "N/A"))
        mb_match = _hw_tokens_match(reg_mb, script_mb) if (mb_has_reg and mb_has_telem) else False if (mb_has_reg or mb_has_telem) else True
        comparison.append({
            "component": "Motherboard",
            "registered": reg_mb,
            "telemetry": script_mb,
            "match": mb_match,
            "status_label": "Coincide OK" if mb_match else ("Pendiente Ejecutar Script (.ps1)" if mb_comps and not mb_has_telem else "Diferencia de Hardware")
        })

        # 2. Procesador (CPU)
        cpu_comps = comp_by_type.get("procesador", []) + comp_by_type.get("microprocesador", []) + comp_by_type.get("cpu", []) + comp_by_type.get("micro", [])
        fallback_cpu = pc.get("processor") if has_twin_evidence else None
        reg_cpu = ", ".join(f"{c['brand_model']} ({c['serial_number'] or 'Sin S/N'})" for c in cpu_comps) if cpu_comps else (fallback_cpu or "Sin registro en Stock")
        cpu_has_reg = bool(cpu_comps or fallback_cpu)
        cpu_has_telem = bool(script_proc and script_proc not in ("Sin reporte de script", "N/A"))
        proc_match = _hw_tokens_match(reg_cpu, script_proc) if (cpu_has_reg and cpu_has_telem) else False if (cpu_has_reg or cpu_has_telem) else True
        comparison.append({
            "component": "Procesador (CPU)",
            "registered": reg_cpu,
            "telemetry": script_proc,
            "match": proc_match,
            "status_label": "Coincide OK" if proc_match else ("Pendiente Ejecutar Script (.ps1)" if cpu_comps and not cpu_has_telem else "Diferencia de Procesador")
        })

        # 3. Memoria RAM
        ram_comps = comp_by_type.get("memoria ram", []) + comp_by_type.get("ram", []) + comp_by_type.get("memoria", [])
        fallback_ram = pc.get("ram_gb") if has_twin_evidence else None
        reg_ram = ", ".join(f"{c['brand_model']} ({c['serial_number'] or 'Sin S/N'})" for c in ram_comps) if ram_comps else (f"{fallback_ram} GB" if fallback_ram else "Sin registro en Stock")
        ram_has_reg = bool(ram_comps or fallback_ram)
        ram_has_telem = bool(script_ram and script_ram not in ("Sin reporte", "N/A"))
        
        ram_match = False
        if ram_has_reg and ram_has_telem:
            if _hw_tokens_match(reg_ram, script_ram):
                ram_match = True
            else:
                total_stock_gb = 0.0
                for c in ram_comps:
                    bm = (c.get("brand_model") or "") + " " + (c.get("component_type") or "")
                    m = re.search(r"(\d+(?:\.\d+)?)\s*GB", bm, re.IGNORECASE)
                    if m:
                        total_stock_gb += float(m.group(1))
                if total_stock_gb == 0.0 and fallback_ram:
                    try:
                        total_stock_gb = float(fallback_ram)
                    except (TypeError, ValueError):
                        pass
                if total_stock_gb == 0.0:
                    gb_matches = re.findall(r"(\d+(?:\.\d+)?)\s*GB", reg_ram, re.IGNORECASE)
                    if gb_matches:
                        total_stock_gb = sum(float(x) for x in gb_matches)
                try:
                    m_telem = re.search(r"[\d.]+", str(script_ram))
                    if m_telem:
                        telem_gb = float(m_telem.group())
                        if total_stock_gb > 0 and telem_gb > 0:
                            diff = abs(total_stock_gb - telem_gb)
                            if diff <= 2.25 or round(telem_gb) == round(total_stock_gb) or int(round(telem_gb)) == int(total_stock_gb):
                                ram_match = True
                            else:
                                for tier in [2, 4, 8, 16, 32, 64, 128]:
                                    if telem_gb <= tier and (tier - telem_gb) <= (tier * 0.35) and total_stock_gb == tier:
                                        ram_match = True
                                        break
                except Exception:
                    pass
        elif not ram_has_reg and not ram_has_telem:
            ram_match = True

        comparison.append({
            "component": "Memoria RAM",
            "registered": reg_ram,
            "telemetry": f"{script_ram} GB" if ram_has_telem and not str(script_ram).lower().endswith("gb") else (script_ram if ram_has_telem else "Sin reporte"),
            "match": ram_match,
            "status_label": "Coincide OK" if ram_match else ("Pendiente Ejecutar Script (.ps1)" if ram_comps and not ram_has_telem else "Diferencia de RAM")
        })

        # 4. Almacenamiento (Disco)
        disk_comps = comp_by_type.get("disco rígido", []) + comp_by_type.get("disco rigido", []) + comp_by_type.get("disco ssd", []) + comp_by_type.get("ssd", []) + comp_by_type.get("disco", []) + comp_by_type.get("almacenamiento", []) + comp_by_type.get("disco rígido / ssd", []) + comp_by_type.get("disco rigido / ssd", [])
        fallback_disk = filter_ignore_devices(pc.get("disk_models")) if has_twin_evidence else None
        reg_disk = ", ".join(f"{c['brand_model']} ({c['serial_number'] or 'Sin S/N'})" for c in disk_comps) if disk_comps else (fallback_disk or "Sin registro en Stock")
        disk_has_reg = bool(disk_comps or fallback_disk)
        disk_has_telem = bool(script_disk and script_disk not in ("Sin reporte de script", "N/A"))
        disk_match = _hw_tokens_match(reg_disk, script_disk) if (disk_has_reg and disk_has_telem) else False if (disk_has_reg or disk_has_telem) else True
        comparison.append({
            "component": "Almacenamiento (Disco)",
            "registered": reg_disk,
            "telemetry": script_disk,
            "match": disk_match,
            "status_label": "Coincide OK" if disk_match else ("Pendiente Ejecutar Script (.ps1)" if disk_comps and not disk_has_telem else "Diferencia de Disco")
        })

        # 5. Otros componentes (Monitores, UPS, etc.) que no reporta WMI
        core_keys = {"motherboard", "placa madre", "mother", "placa", 
                     "procesador", "microprocesador", "cpu", "micro",
                     "memoria ram", "ram", "memoria",
                     "disco rígido", "disco rigido", "disco ssd", "ssd", "disco", "almacenamiento", "disco rígido / ssd", "disco rigido / ssd"}
        
        for ctype, comps_list in comp_by_type.items():
            if ctype not in core_keys:
                reg_str = ", ".join(f"{c.get('brand_model', '')} ({c.get('serial_number') or 'Sin S/N'})" for c in comps_list)
                comparison.append({
                    "component": str(comps_list[0].get("component_type") or ctype).title(),
                    "registered": reg_str,
                    "telemetry": "N/A (No reportable por WMI)",
                    "match": True,
                    "status_label": "Asignado en Patrimonio"
                })

        return comparison
    finally:
        if close_conn:
            conn_ctx.__exit__(None, None, None)
