from services.asset_validation import (
    get_pc_validation_comparison,
    is_ignored_storage_component,
    resolve_build_order_action,
    resolve_effective_validation_status,
)
from database.db_core import get_db_connection
from utils.auth import list_technician_users
from datetime import datetime
import json
import re
import unicodedata


def _clean_str(s):
    if not s:
        return ""
    s_norm = unicodedata.normalize('NFD', str(s))
    return ''.join(c for c in s_norm if unicodedata.category(c) != 'Mn').lower().strip()


def _is_inactive_inventory_status(status):
    return _clean_str(status) in {"stock", "retirado", "scrap"}


def _component_family(component_type):
    ctype = _clean_str(component_type)
    if any(token in ctype for token in ("monitor", "pantalla")):
        return "monitor"
    if any(token in ctype for token in ("procesador", "micro", "cpu")):
        return "processor"
    if any(token in ctype for token in ("motherboard", "placa madre", "mother")):
        return "motherboard"
    if any(token in ctype for token in ("ram", "memoria")):
        return "ram"
    if any(token in ctype for token in ("disco", "almacenamiento", "ssd", "hdd")):
        return "disk"
    if any(token in ctype for token in ("gabinete", "chasis")):
        return "case"
    if any(token in ctype for token in ("fuente", "psu", "power")):
        return "psu"
    return ctype or "other"


def _normalize_model_for_match(value):
    return re.sub(r"\s+", " ", _clean_str(value))


def _is_real_serial(value):
    serial = (value or "").strip().upper()
    return bool(serial) and serial not in {"N/A", "SIN S/N", "SIN N/S", "NONE", "NULL"}


def _models_look_equivalent(left, right):
    left_norm = _normalize_model_for_match(left)
    right_norm = _normalize_model_for_match(right)
    if not left_norm or not right_norm:
        return False
    return left_norm in right_norm or right_norm in left_norm


def _component_matches_hardware(component, hw_model, hw_serial):
    comp_serial = (component.get("serial_number") or "").strip().upper()
    hw_serial_norm = (hw_serial or "").strip().upper()
    if _is_real_serial(comp_serial) and _is_real_serial(hw_serial_norm) and comp_serial == hw_serial_norm:
        return True
    return _models_look_equivalent(component.get("brand_model"), hw_model)


def _is_autogenerated_component(item):
    serial = (item.get("serial_number") or "").strip().upper()
    return bool(item.get("is_autogenerated_id")) or serial.startswith("INT-")


def find_autogenerated_shadow_components(items):
    real_components_by_key = {}
    for raw_item in items or []:
        item = dict(raw_item)
        if _is_autogenerated_component(item):
            continue
        family = _component_family(item.get("component_type"))
        model = _normalize_model_for_match(item.get("brand_model") or item.get("model") or item.get("brand"))
        if family and model and (family, model) not in real_components_by_key:
            real_components_by_key[(family, model)] = item

    candidates = []
    for raw_item in items or []:
        item = dict(raw_item)
        if not _is_autogenerated_component(item):
            continue
        if item.get("ignore_autogenerated_duplicate"):
            continue
        family = _component_family(item.get("component_type"))
        model = _normalize_model_for_match(item.get("brand_model") or item.get("model") or item.get("brand"))
        shadowing_real = real_components_by_key.get((family, model))
        if not shadowing_real:
            continue
        item["shadowed_by_serial_number"] = shadowing_real.get("serial_number")
        item["shadowed_by_component_type"] = shadowing_real.get("component_type")
        item["shadowed_by_brand_model"] = shadowing_real.get("brand_model")
        candidates.append(item)
    return candidates


def find_autogenerated_shadow_components_by_owner(items):
    grouped_items = {}
    for raw_item in items or []:
        item = dict(raw_item)
        assigned_pc = _clean_str(item.get("assigned_pc"))
        if assigned_pc:
            owner_key = f"pc:{assigned_pc}"
        elif item.get("build_order_id"):
            owner_key = f"bo:{item.get('build_order_id')}"
        else:
            assigned_user = _clean_str(item.get("assigned_user"))
            assigned_fuero = _clean_str(item.get("assigned_fuero"))
            owner_key = f"user:{assigned_user}:{assigned_fuero}" if assigned_user or assigned_fuero else ""
        if not owner_key:
            continue
        grouped_items.setdefault(owner_key, []).append(item)

    candidates = []
    for owner_items in grouped_items.values():
        candidates.extend(find_autogenerated_shadow_components(owner_items))
    return candidates


def _dedupe_autogenerated_shadow_components(items):
    shadow_serials = {
        (item.get("serial_number") or "").strip().upper()
        for item in find_autogenerated_shadow_components(items)
        if item.get("serial_number")
    }
    return [
        dict(item)
        for item in items
        if (item.get("serial_number") or "").strip().upper() not in shadow_serials
    ]


def _filter_display_components_for_pc(components, monitors_detail, pc_name, linked_bo_id=None):
    normalized_pc = _clean_str(pc_name)
    normalized_bo_id = str(linked_bo_id) if linked_bo_id is not None else None

    def should_keep(item):
        if not item:
            return False
        if is_ignored_storage_component(item):
            return False
        if _is_inactive_inventory_status(item.get("status")):
            return False

        assigned_pc = _clean_str(item.get("assigned_pc"))
        item_bo_id = item.get("build_order_id")
        normalized_item_bo_id = str(item_bo_id) if item_bo_id is not None else None

        if item.get("source") == "audit" and not assigned_pc and not normalized_item_bo_id:
            return False

        if assigned_pc and assigned_pc != normalized_pc:
            return False
        if (
            normalized_bo_id
            and normalized_item_bo_id
            and normalized_item_bo_id != normalized_bo_id
            and assigned_pc != normalized_pc
        ):
            return False
        return True

    filtered_components = [dict(component) for component in components if should_keep(component)]
    filtered_monitors = [dict(monitor) for monitor in monitors_detail if should_keep(monitor)]

    return (
        _dedupe_autogenerated_shadow_components(filtered_components),
        _dedupe_autogenerated_shadow_components(filtered_monitors),
    )


def _infer_disk_kind(model, speed_text):
    model_text = (model or "").strip()
    speed_value = (speed_text or "").strip()
    combined = f"{model_text} {speed_value}".upper()

    rpm_match = re.search(r"(\d+)\s*RPM", combined)
    if rpm_match:
        rpm = int(rpm_match.group(1))
        if rpm > 0:
            return f"HDD {rpm} RPM"

    if any(token in combined for token in ("SSD", "NVME", "M.2", "SOLID")):
        return "SSD"

    if re.search(r"\b(SN[VMP]?\w*|SU\d+|EVO|KINGSTON|ADATA)\b", combined) and "HITACHI" not in combined:
        return "SSD"

    if any(token in combined for token in ("HITACHI", "WD ", "WESTERN DIGITAL", "SEAGATE", "TOSHIBA", "HUA7")):
        return "HDD"

    if "FIXED HARD DISK" in combined or "HDD" in combined:
        return "HDD"

    return "Tipo no detectado"


def _build_disk_summary_lines(disk_models, disk_speeds):
    models = [part.strip() for part in (disk_models or "").split("|") if part.strip()]
    speed_parts = [part.strip() for part in (disk_speeds or "").split("|") if part.strip()]
    speed_map = {}

    for part in speed_parts:
        if ":" in part:
            model_name, kind = part.split(":", 1)
            speed_map[model_name.strip().upper()] = kind.strip()

    lines = []
    for model_entry in models:
        model_name = model_entry.split(" (")[0].strip()
        kind = speed_map.get(model_name.upper(), "")
        if not kind or kind.upper() in ("RPM", "0 RPM", "N/A"):
            kind = _infer_disk_kind(model_entry, kind)
        lines.append(f"{model_entry} - {kind}")

    return lines


def _build_quick_health_summary(pc):
    telemetry_raw = pc.get("telemetry_snapshot") or pc.get("full_json_data")
    telemetry = {}
    if telemetry_raw:
        try:
            telemetry = json.loads(telemetry_raw)
        except Exception:
            telemetry = {}

    health = telemetry.get("Salud", {}) if isinstance(telemetry, dict) else {}
    system = telemetry.get("Sistema", {}) if isinstance(telemetry, dict) else {}

    uptime_days = health.get("Uptime_Dias")
    raw_critical_events = health.get("Eventos_Criticos") or []
    updates = health.get("Actualizaciones") or {}
    connectivity = health.get("Conectividad") or {}

    def _is_noise_event(event):
        source = (event.get("Source") or "").strip().upper()
        msg = (event.get("Msg") or "").strip().lower()
        if source == "DCOM" and "no se encontr" in msg and "descripci" in msg:
            return True
        return False

    critical_events = [event for event in raw_critical_events if not _is_noise_event(event)]

    update_age_days = updates.get("DiasSinActualizar")
    try:
        update_age_days = int(float(update_age_days))
    except Exception:
        update_age_days = None

    gateway_target = (connectivity.get("Gateway") or "").strip()
    printer_target = (connectivity.get("PrinterTarget") or "").strip()
    gateway_ok = int(connectivity.get("GatewayOk") or 0)
    printer_ok = int(connectivity.get("PrinterOk") or 0)

    gateway_known = gateway_target not in ("", "N/A")
    printer_known = printer_target not in ("", "N/A")
    connectivity_issue_count = 0
    if gateway_known and not gateway_ok:
        connectivity_issue_count += 1
    if printer_known and not printer_ok:
        connectivity_issue_count += 1

    stale_updates = update_age_days is not None and update_age_days > 90
    aging_updates = update_age_days is not None and update_age_days > 45

    status = "ok"
    summary_label = "Equipo sano"
    if (
        pc.get("alerta_nombre_duplicado")
        or pc.get("alerta_uptime")
        or stale_updates
        or connectivity_issue_count >= 2
    ):
        status = "danger"
        summary_label = "Revisión técnica recomendada"
    elif (
        pc.get("alerta_ram_baja")
        or pc.get("alerta_sin_impresora")
        or critical_events
        or aging_updates
        or connectivity_issue_count == 1
    ):
        status = "warning"
        summary_label = "Conviene revisar pronto"

    return {
        "status": status,
        "summary_label": summary_label,
        "uptime_days": uptime_days,
        "critical_event_count": len(critical_events),
        "update_age_days": update_age_days,
        "connectivity_issue_count": connectivity_issue_count,
        "gateway_known": gateway_known,
        "printer_known": printer_known,
        "office": system.get("Office") or pc.get("office_version") or "N/A",
        "os": system.get("OsName") or pc.get("os_name") or "N/A",
        "has_telemetry": bool(telemetry),
    }


def _empty_quick_health_summary():
    return {
        "status": "warning",
        "summary_label": "Sin telemetría disponible",
        "uptime_days": None,
        "critical_event_count": 0,
        "update_age_days": None,
        "connectivity_issue_count": 0,
        "gateway_known": False,
        "printer_known": False,
        "office": "N/A",
        "os": "N/A",
        "has_telemetry": False,
    }

def _parse_hardware_components(pc):
    """
    Formatea y estructura los componentes internos (Motherboard, RAM, Discos, CPU) 
    extrayendo marcas, modelos y números de serie físicos.
    """
    mb_raw = pc.get("motherboard_model") or "N/A"
    ram_raw = pc.get("ram_detalles") or "N/A"
    disk_raw = pc.get("disk_models") or "N/A"
    proc_raw = pc.get("processor") or "N/A"

    # Motherboard
    mb_info = {"model": mb_raw, "serial": "N/A"}
    if " (SN: " in mb_raw:
        parts = mb_raw.split(" (SN: ")
        mb_info["model"] = parts[0].strip()
        mb_info["serial"] = parts[1].replace(")", "").strip()

    # RAM Modules
    ram_list = []
    if ram_raw and ram_raw != "N/A":
        for module in ram_raw.split("|"):
            mod_str = module.strip()
            if not mod_str: continue
            sn = "N/A"
            if " (SN: " in mod_str:
                m_parts = mod_str.split(" (SN: ")
                spec = m_parts[0].strip()
                sn = m_parts[1].replace(")", "").strip()
            else:
                spec = mod_str
            ram_list.append({"spec": spec, "serial": sn})

    # Disks
    disk_list = []
    if disk_raw and disk_raw != "N/A":
        for disk in disk_raw.split("|"):
            d_str = disk.strip()
            if not d_str: continue
            sn = "N/A"
            if " [SN: " in d_str:
                d_parts = d_str.split(" [SN: ")
                model = d_parts[0].strip()
                sn = d_parts[1].replace("]", "").strip()
            else:
                model = d_str
            disk_list.append({"model": model, "serial": sn})

def _parse_single_monitor_entry(m_str):
    m_str = m_str.strip()
    if not m_str:
        return None
    sn_match = re.search(r'[\(\[\{]\s*(?:SN|S/N|Serial|S\\N)\s*[:=]\s*([^\)\]\}]+)[\)\]\}]', m_str, re.IGNORECASE)
    if sn_match:
        sn = sn_match.group(1).strip()
        model = m_str[:sn_match.start()].strip()
        if not model:
            model = m_str[sn_match.end():].strip() or "Monitor"
        return {"model": model, "serial": sn}

    return {"model": m_str, "serial": "N/A"}


def _parse_monitors_string(mon_raw, full_json=None):
    mon_list = []
    if full_json and isinstance(full_json, dict):
        json_mons = full_json.get("Monitors_Detail") or full_json.get("Monitors_List") or full_json.get("Detected_Monitors")
        if isinstance(json_mons, list) and len(json_mons) > 0:
            for item in json_mons:
                if isinstance(item, dict):
                    m_model = item.get("Model") or item.get("model") or item.get("Name") or "Monitor"
                    m_sn = item.get("SerialNumber") or item.get("serial") or item.get("SN") or "N/A"
                    mon_list.append({"model": str(m_model).strip(), "serial": str(m_sn).strip()})
                elif isinstance(item, str) and item.strip():
                    parsed = _parse_single_monitor_entry(item)
                    if parsed: mon_list.append(parsed)

    if mon_list:
        return mon_list

    if not mon_raw or mon_raw in ("N/A", "None", ""):
        if full_json and isinstance(full_json, dict) and full_json.get("Monitors"):
            mon_raw = str(full_json.get("Monitors"))

    if not mon_raw or mon_raw in ("N/A", "None", ""):
        return []

    normalized_raw = mon_raw.replace("\r\n", "|").replace("\n", "|").replace(";", "|")
    
    if "|" not in normalized_raw and "," in normalized_raw:
        if "SN:" in normalized_raw.upper() or "S/N:" in normalized_raw.upper() or normalized_raw.count(",") > 1:
            normalized_raw = re.sub(r',\s*(?=[A-Za-z0-9])', '|', normalized_raw)

    entries = [part.strip() for part in normalized_raw.split("|") if part.strip()]
    for entry in entries:
        if not entry or entry.upper() in ("N/A", "NONE"):
            continue
        parsed = _parse_single_monitor_entry(entry)
        if parsed:
            mon_list.append(parsed)

    return mon_list


def _parse_hardware_components(pc):
    """
    Formatea y estructura los componentes internos (Motherboard, RAM, Discos, CPU, Monitores) 
    extrayendo marcas, modelos y números de serie físicos.
    """
    mb_raw = pc.get("motherboard_model") or "N/A"
    ram_raw = pc.get("ram_detalles") or "N/A"
    disk_raw = pc.get("disk_models") or "N/A"
    proc_raw = pc.get("processor") or "N/A"

    # Keyboard & Mouse (from full_json_data or pc dict if present)
    full_json = {}
    if pc.get("full_json_data"):
        try:
            import json
            full_json = json.loads(pc["full_json_data"])
        except Exception: pass

    # Motherboard
    mb_info = {"model": mb_raw, "serial": "N/A"}
    if " (SN: " in mb_raw:
        parts = mb_raw.split(" (SN: ")
        mb_info["model"] = parts[0].strip()
        mb_info["serial"] = parts[1].replace(")", "").strip()

    # RAM Modules
    ram_list = []
    if ram_raw and ram_raw != "N/A":
        for module in ram_raw.split("|"):
            mod_str = module.strip()
            if not mod_str: continue
            sn = "N/A"
            if " (SN: " in mod_str:
                m_parts = mod_str.split(" (SN: ")
                spec = m_parts[0].strip()
                sn = m_parts[1].replace(")", "").strip()
            else:
                spec = mod_str
            ram_list.append({"spec": spec, "serial": sn})

    # Disks
    disk_list = []
    if disk_raw and disk_raw != "N/A":
        for disk in disk_raw.split("|"):
            d_str = disk.strip()
            if not d_str: continue
            sn = "N/A"
            if " [SN: " in d_str:
                d_parts = d_str.split(" [SN: ")
                model = d_parts[0].strip()
                sn = d_parts[1].replace("]", "").strip()
            else:
                model = d_str
            disk_list.append({"model": model, "serial": sn})

    # Monitors
    mon_raw = pc.get("monitors") or "N/A"
    mon_list = _parse_monitors_string(mon_raw, full_json)
    
    keyboard_model = full_json.get("Keyboard_Model") or "Teclado USB Estándar"
    if not keyboard_model or keyboard_model in ("N/A", "None", ""):
        keyboard_model = "Teclado USB Estándar"

    mouse_model = full_json.get("Mouse_Model") or "Mouse Óptico USB Estándar"
    if not mouse_model or mouse_model in ("N/A", "None", ""):
        mouse_model = "Mouse Óptico USB Estándar"

    # Printer
    printer_info = {
        "model": pc.get("printer_model") or "N/A",
        "port": pc.get("printer_port") or "N/A",
        "serial": pc.get("printer_sn") or "N/A"
    }

    return {
        "motherboard": mb_info,
        "ram_modules": ram_list,
        "disks": disk_list,
        "monitors": mon_list,
        "keyboard": keyboard_model,
        "mouse": mouse_model,
        "printer": printer_info,
        "processor": proc_raw
    }


def _enrich_components_with_remitos(conn, pc_components, hardware_components):
    comp_dicts = [dict(c) for c in pc_components]
    stock_monitors = [c for c in comp_dicts if "MONITOR" in (c.get("component_type") or "").strip().upper()]
    hw_monitors = hardware_components.get("monitors") or []

    bo_map = {}
    try:
        bo_rows = conn.execute("SELECT id, code, target_pc_name, target_user, target_fuero FROM build_orders").fetchall()
        for b in bo_rows:
            bo_map[b["id"]] = dict(b)
    except Exception:
        pass
    
    monitors_detail = []
    serial_to_db_comp = {}
    for c in comp_dicts:
        sn = (c.get("serial_number") or "").strip().upper()
        if sn and sn not in ("N/A", "SIN S/N", ""):
            serial_to_db_comp[sn] = c

    if not hw_monitors and stock_monitors:
        for sm in stock_monitors:
            b_id = sm.get("build_order_id")
            b_code = bo_map.get(b_id, {}).get("code") if b_id else None
            monitors_detail.append({
                "brand_model": sm.get("brand_model") or "Monitor Estándar",
                "serial_number": sm.get("serial_number") or "Sin S/N",
                "invoice_number": sm.get("invoice_number"),
                "oc_number": sm.get("oc_number"),
                "supplier": sm.get("supplier"),
                "status": sm.get("status") or "Stock",
                "build_order_id": b_id,
                "bo_code": b_code,
                "assigned_pc": sm.get("assigned_pc"),
                "assigned_user": sm.get("assigned_user"),
                "assigned_fuero": sm.get("assigned_fuero"),
                "source": "stock"
            })
    else:
        unassigned_stock_monitors = list(stock_monitors)
        
        for hw_m in hw_monitors:
            m_model = hw_m.get("model") or "Monitor Estándar"
            m_sn = (hw_m.get("serial") or "").strip()
            m_sn_upper = m_sn.upper()
            
            matched_stock = None
            
            # A) Buscar coincidencia exacta por S/N
            if m_sn_upper and m_sn_upper not in ("N/A", "SIN S/N", ""):
                for sm in unassigned_stock_monitors:
                    sm_sn = (sm.get("serial_number") or "").strip().upper()
                    if sm_sn == m_sn_upper:
                        matched_stock = sm
                        break

            # B) Si no hay match por S/N, tomar coincidencia por modelo o monitor de stock genérico/sin S/N
            if not matched_stock and unassigned_stock_monitors:
                for sm in unassigned_stock_monitors:
                    sm_sn = (sm.get("serial_number") or "").strip().upper()
                    if sm_sn in ("N/A", "SIN S/N", ""):
                        matched_stock = sm
                        break

                if not matched_stock and m_model:
                    m_mod_clean = _clean_str(m_model)
                    for sm in unassigned_stock_monitors:
                        sm_mod_clean = _clean_str(sm.get("brand_model"))
                        if m_mod_clean and sm_mod_clean and (m_mod_clean in sm_mod_clean or sm_mod_clean in m_mod_clean):
                            matched_stock = sm
                            break

                if not matched_stock and len(unassigned_stock_monitors) == 1:
                    matched_stock = unassigned_stock_monitors[0]

            if matched_stock:
                unassigned_stock_monitors.remove(matched_stock)

            # C) Buscar Remito/OC en la tabla `components` si m_sn_upper existe en DB
            matched_db_extra = None
            if m_sn_upper and m_sn_upper not in ("N/A", "SIN S/N", ""):
                if m_sn_upper in serial_to_db_comp:
                    matched_db_extra = serial_to_db_comp[m_sn_upper]
                else:
                    row = conn.execute(
                        "SELECT * FROM components WHERE UPPER(serial_number) = %s LIMIT 1",
                        (m_sn_upper,)
                    ).fetchone()
                    if row:
                        matched_db_extra = dict(row)

            target_src = matched_stock or matched_db_extra or {}
            final_remito = target_src.get("invoice_number")
            final_oc = target_src.get("oc_number")
            final_supplier = target_src.get("supplier")
            final_status = target_src.get("status") or "Auditoria"
            b_id = target_src.get("build_order_id")
            b_code = bo_map.get(b_id, {}).get("code") if b_id else None
            
            final_model = m_model
            if final_model in ("Monitor", "Monitor Estándar", "Genérico") and matched_stock and matched_stock.get("brand_model"):
                final_model = matched_stock["brand_model"]

            target_serial = target_src.get("serial_number")
            if matched_stock and _is_real_serial(target_serial):
                final_sn = target_serial
            elif _is_real_serial(m_sn):
                final_sn = m_sn
            else:
                final_sn = target_serial if target_serial else "Sin S/N"

            # Determine source: if it was found in the DB but NOT in the PC's unassigned_stock_monitors,
            # it means it is physically plugged in but NOT officially assigned to this PC (e.g. in Stock).
            source_type = "merged"
            if target_src == matched_db_extra:
                source_type = "audit"

            monitors_detail.append({
                "id": target_src.get("id"),
                "brand_model": final_model,
                "serial_number": final_sn if final_sn else "Sin S/N",
                "invoice_number": final_remito,
                "oc_number": final_oc,
                "supplier": final_supplier,
                "status": final_status,
                "build_order_id": b_id,
                "bo_code": b_code,
                "assigned_pc": target_src.get("assigned_pc"),
                "assigned_user": target_src.get("assigned_user"),
                "assigned_fuero": target_src.get("assigned_fuero"),
                "source": source_type
            })

    # 3. Componentes unificados
    all_unified_components = []
    existing_serials = {(c.get("serial_number") or "").strip().upper() for c in comp_dicts if _is_real_serial(c.get("serial_number"))}
    for c in comp_dicts:
        if "MONITOR" not in (c.get("component_type") or "").strip().upper():
            c_dict = dict(c)
            b_id = c_dict.get("build_order_id")
            c_dict["bo_code"] = bo_map.get(b_id, {}).get("code") if b_id else None
            all_unified_components.append(c_dict)

    for m in monitors_detail:
        all_unified_components.append({
            "id": m.get("id"),
            "component_type": "Monitor",
            "brand_model": m.get("brand_model") or "Monitor Estándar",
            "serial_number": m.get("serial_number") or "Sin S/N",
            "invoice_number": m.get("invoice_number"),
            "oc_number": m.get("oc_number"),
            "supplier": m.get("supplier"),
            "status": m.get("status") or "Stock",
            "build_order_id": m.get("build_order_id"),
            "bo_code": m.get("bo_code"),
            "assigned_pc": m.get("assigned_pc"),
            "assigned_user": m.get("assigned_user"),
            "assigned_fuero": m.get("assigned_fuero"),
            "source": m.get("source", "merged")
        })

    official_mb_components = [
        c for c in all_unified_components
        if _component_family(c.get("component_type")) == "motherboard" and c.get("source") != "audit"
    ]
    has_mb_in_components = bool(official_mb_components)
    # Motherboard
    mb_hw = hardware_components.get("motherboard") or {}
    mb_model = mb_hw.get("model")
    mb_sn = mb_hw.get("serial")
    if mb_model and mb_model != "N/A":
        mb_sn_upper = (mb_sn or "").strip().upper()
        has_real_sn = _is_real_serial(mb_sn_upper)
        if (has_real_sn and mb_sn_upper not in existing_serials) or (not has_real_sn and not has_mb_in_components):
            matched_db = None
            if has_real_sn:
                row = conn.execute("SELECT * FROM components WHERE UPPER(serial_number) = %s LIMIT 1", (mb_sn_upper,)).fetchone()
                if row: matched_db = dict(row)
            if not official_mb_components:
                all_unified_components.append({
                    "component_type": "Motherboard",
                    "brand_model": mb_model,
                    "serial_number": mb_sn if mb_sn else "N/A",
                    "invoice_number": matched_db.get("invoice_number") if matched_db else None,
                    "oc_number": matched_db.get("oc_number") if matched_db else None,
                    "supplier": matched_db.get("supplier") if matched_db else None,
                    "source": "audit"
                })

    # Procesador
    proc_hw = hardware_components.get("processor")
    if proc_hw and proc_hw != "N/A":
        if not any(any(tok in (c.get("component_type") or "").upper() for tok in ["PROCESADOR", "CPU", "MICRO"]) for c in all_unified_components):
            all_unified_components.append({
                "component_type": "Procesador",
                "brand_model": proc_hw,
                "serial_number": "N/A",
                "invoice_number": None,
                "oc_number": None,
                "supplier": None,
                "source": "audit"
            })

    # RAM
    has_ram_in_components = any(any(tok in (c.get("component_type") or "").upper() for tok in ["RAM", "MEMORIA"]) for c in all_unified_components)
    for ram in (hardware_components.get("ram_modules") or []):
        r_sn = (ram.get("serial") or "").strip()
        r_sn_upper = r_sn.upper()
        has_real_sn = r_sn_upper and r_sn_upper not in ("N/A", "SIN S/N")
        if (has_real_sn and r_sn_upper not in existing_serials) or (not has_real_sn and not has_ram_in_components):
            matched_db = None
            if has_real_sn:
                row = conn.execute("SELECT * FROM components WHERE UPPER(serial_number) = %s LIMIT 1", (r_sn_upper,)).fetchone()
                if row: matched_db = dict(row)
            all_unified_components.append({
                "component_type": "Memoria RAM",
                "brand_model": ram.get("spec") or "RAM",
                "serial_number": r_sn if r_sn else "N/A",
                "invoice_number": matched_db.get("invoice_number") if matched_db else None,
                "oc_number": matched_db.get("oc_number") if matched_db else None,
                "supplier": matched_db.get("supplier") if matched_db else None,
                "source": "audit"
            })

    # Discos
    official_disk_components = [
        c for c in all_unified_components
        if _component_family(c.get("component_type")) == "disk" and c.get("source") != "audit"
    ]
    hardware_disks = []
    for disk in (hardware_components.get("disks") or []):
        d_model = (disk.get("model") or "").upper()
        # Ignorar pendrives / almacenamiento extraíble USB para que no se autogeneren como discos fijos patrimoniales
        if any(usb_tok in d_model for usb_tok in [
            "USB DEVICE", "USB FLASH", "PENDRIVE", "DATATRAVELER", "CRUZER", 
            "CARD READER", "CARD_READER", "SD READER", "MS READER", "CF READER", 
            "SM READER", "GENERIC USB STORAGE", "USB CR READER", "SD/MMC CARD"
        ]):
            continue
        hardware_disks.append(disk)

    unmatched_hardware_disks = [
        disk for disk in hardware_disks
        if not any(_component_matches_hardware(comp, disk.get("model"), disk.get("serial")) for comp in official_disk_components)
    ]
    max_audit_disks_to_add = max(0, len(hardware_disks) - len(official_disk_components))

    for disk in unmatched_hardware_disks[:max_audit_disks_to_add]:
        d_sn = (disk.get("serial") or "").strip()
        d_sn_upper = d_sn.upper()
        has_real_sn = _is_real_serial(d_sn_upper)
        if has_real_sn and d_sn_upper in existing_serials:
            continue
        if has_real_sn or not official_disk_components:
            matched_db = None
            if has_real_sn:
                row = conn.execute("SELECT * FROM components WHERE UPPER(serial_number) = %s LIMIT 1", (d_sn_upper,)).fetchone()
                if row: matched_db = dict(row)
            all_unified_components.append({
                "component_type": "Disco Rígido / SSD",
                "brand_model": disk.get("model") or "Disco",
                "serial_number": d_sn if d_sn else "N/A",
                "invoice_number": matched_db.get("invoice_number") if matched_db else None,
                "oc_number": matched_db.get("oc_number") if matched_db else None,
                "supplier": matched_db.get("supplier") if matched_db else None,
                "source": "audit"
            })

    return monitors_detail, all_unified_components


def get_pc_detail_context(pc_name):
    """Obtiene todo el contexto necesario para renderizar pc_detail.html y public_asset_info.html."""
    ad_users_list = []
    with get_db_connection() as conn:
        pc = conn.execute("""
            SELECT p.*, COALESCE(u.real_name, au.display_name) as ad_real_name 
            FROM pcs p 
            LEFT JOIN ad_users u ON LOWER(SUBSTRING_INDEX(p.last_user, '\\\\', -1)) = u.username 
            LEFT JOIN app_users au ON LOWER(SUBSTRING_INDEX(p.last_user, '\\\\', -1)) = au.username
            WHERE p.pc_name = %s
        """, (pc_name,)).fetchone()
        
        # Fallback 1: Buscar si pc_name es S/N de un componente asignado
        if not pc:
            comp_match = conn.execute("""
                SELECT assigned_pc FROM components 
                WHERE serial_number = %s AND assigned_pc IS NOT NULL AND assigned_pc != '' 
                LIMIT 1
            """, (pc_name,)).fetchone()
            if comp_match:
                pc_name = comp_match["assigned_pc"]
                pc = conn.execute("""
                    SELECT p.*, COALESCE(u.real_name, au.display_name) as ad_real_name 
                    FROM pcs p 
                    LEFT JOIN ad_users u ON LOWER(SUBSTRING_INDEX(p.last_user, '\\\\', -1)) = u.username 
                    LEFT JOIN app_users au ON LOWER(SUBSTRING_INDEX(p.last_user, '\\\\', -1)) = au.username
                    WHERE p.pc_name = %s
                """, (pc_name,)).fetchone()

        # Fallback 2: Buscar si pc_name está en las columnas auditadas de pcs
        if not pc:
            like_pat = f"%{pc_name}%"
            pc_match = conn.execute("""
                SELECT pc_name FROM pcs 
                WHERE monitors LIKE %s OR motherboard_model LIKE %s OR disk_models LIKE %s OR ram_detalles LIKE %s 
                LIMIT 1
            """, (like_pat, like_pat, like_pat, like_pat)).fetchone()
            if pc_match:
                pc_name = pc_match["pc_name"]
                pc = conn.execute("""
                    SELECT p.*, COALESCE(u.real_name, au.display_name) as ad_real_name 
                    FROM pcs p 
                    LEFT JOIN ad_users u ON LOWER(SUBSTRING_INDEX(p.last_user, '\\\\', -1)) = u.username 
                    LEFT JOIN app_users au ON LOWER(SUBSTRING_INDEX(p.last_user, '\\\\', -1)) = au.username
                    WHERE p.pc_name = %s
                """, (pc_name,)).fetchone()

        # Fallback 3: Componente individual de inventario
        if not pc:
            standalone = conn.execute(
                "SELECT * FROM components WHERE serial_number = %s OR id = %s LIMIT 1",
                (pc_name, int(pc_name) if pc_name.isdigit() else -1)
            ).fetchone()
            if standalone:
                c_dict = dict(standalone)
                is_mon = (c_dict.get("component_type") or "").upper() == "MONITOR"
                mon_list = [{
                    "brand_model": c_dict.get("brand_model") or "Monitor",
                    "serial_number": c_dict.get("serial_number") or "Sin S/N",
                    "invoice_number": c_dict.get("invoice_number"),
                    "oc_number": c_dict.get("oc_number"),
                    "supplier": c_dict.get("supplier"),
                    "source": "stock"
                }] if is_mon else []
                return {
                    "is_standalone_component": True,
                    "pc_name": f"COMPONENTE: {c_dict.get('component_type')} - {c_dict.get('brand_model')}",
                    "pc": {
                        "pc_name": c_dict.get("serial_number") or f"COMP-{c_dict.get('id')}",
                        "last_user": c_dict.get("assigned_user") or "Sin asignar",
                        "fuero": c_dict.get("assigned_fuero") or "Stock / Depósito",
                        "validation_status": "validado" if c_dict.get("status") == "Installed" else "pendiente"
                    },
                    "pc_components": [c_dict],
                    "all_unified_components": [c_dict],
                    "monitors_detail": mon_list,
                    "hardware_components": {"motherboard": {"model": "N/A", "serial": "N/A"}, "ram_modules": [], "disks": [], "monitors": mon_list, "processor": "N/A"},
                    "oc_list": [c_dict["oc_number"]] if c_dict.get("oc_number") else [],
                    "invoice_list": [c_dict["invoice_number"]] if c_dict.get("invoice_number") else [],
                    "quick_health": _empty_quick_health_summary(),
                }
        # Fallback 4: Buscar en build_orders / build_order_items por target_pc_name o pc_name
        if not pc:
            bo_match = conn.execute("""
                SELECT bo.*, boi.pc_name as item_pc_name
                FROM build_orders bo
                LEFT JOIN build_order_items boi ON boi.build_order_id = bo.id
                WHERE LOWER(bo.target_pc_name) = %s OR LOWER(boi.pc_name) = %s
                LIMIT 1
            """, (pc_name.lower(), pc_name.lower())).fetchone()
            
            if bo_match:
                bo_dict = dict(bo_match)
                pc_name_resolved = bo_dict.get("target_pc_name") or bo_dict.get("item_pc_name") or pc_name
                pc_name = pc_name_resolved
                pc = {
                    "pc_name": pc_name_resolved,
                    "last_user": bo_dict.get("target_user") or "Sin asignar",
                    "fuero": bo_dict.get("target_fuero") or "General",
                    "validation_status": "pendiente"
                }

        if not pc:
            return None

        tareas = [dict(row) for row in conn.execute("""
            SELECT id, pc_name, created_at, descripcion, estado, solicitante, assigned_to, completed_by
            FROM tasks WHERE pc_name = %s ORDER BY created_at DESC
        """, (pc_name,)).fetchall()]
        
        # Attach AD matches if this is a generic PC
        if 'generica' in pc_name.lower():
            from blueprints.bp_tasks import _attach_task_user_matches
            tareas = _attach_task_user_matches(tareas, conn)
        
        technicians = list_technician_users()
        
        audit_logs = conn.execute("SELECT * FROM audit_logs WHERE pc_name = %s ORDER BY changed_at DESC", (pc_name,)).fetchall()
        
        all_pcs = conn.execute("""
            SELECT p.pc_name, p.fuero, p.last_user, a.real_name 
            FROM pcs p 
            LEFT JOIN ad_users a ON LOWER(SUBSTRING_INDEX(p.last_user, '\\\\', -1)) = a.username 
            WHERE p.is_active=1 
            ORDER BY p.pc_name
        """).fetchall()
        
        pc_ups_list = conn.execute('''
            SELECT u.*, b.serial_number as battery_code FROM ups_inventory u
            LEFT JOIN components b ON u.assigned_battery_id = b.id
            WHERE u.assigned_pc = %s
        ''', (pc_name,)).fetchall()
        
        # Compartición de impresoras
        sharing_pc_data = None
        if pc["printer_port"] and pc["printer_port"].startswith("\\\\"):
            parts = pc["printer_port"].split("\\")
            if len(parts) >= 3:
                potential_host = parts[2].upper()
                sharing_pc_data = conn.execute(
                    "SELECT pc_name, is_active, printer_port, printer_sn, printer_model FROM pcs WHERE pc_name = %s OR ip_address = %s LIMIT 1", 
                    (potential_host, potential_host)
                ).fetchone()
        
        clients_using_this_printer = []
        if pc["pc_name"] and (pc["pc_name"].upper() not in ('PC GENERICA', 'INFRAESTRUCTURA', 'PC-GENERICA')):
            pat_name = f"%\\\\\\\\{pc['pc_name'].upper()}\\\\%"
            pat_ip = f"%\\\\\\\\{pc['ip_address']}\\\\%" if pc['ip_address'] and pc['ip_address'] != 'N/A' else None
            query = "SELECT pc_name FROM pcs WHERE is_active=1 AND UPPER(printer_port) LIKE %s"
            params = [pat_name]
            if pat_ip:
                query += " OR UPPER(printer_port) LIKE %s"; params.append(pat_ip)
            clients_using_this_printer = conn.execute(query, tuple(params)).fetchall()
        
        available_ups = conn.execute("SELECT id, code, model FROM ups_inventory WHERE assigned_pc IS NULL").fetchall()
        pc_components = conn.execute('''
            SELECT DISTINCT c.id, c.serial_number, c.component_type, c.brand_model, c.status, c.assigned_to_component_id,
                   c.is_autogenerated_id,
                   c.oc_number, c.invoice_number, c.supplier, c.assigned_user, c.assigned_fuero, c.assigned_pc, c.build_order_id
            FROM components c
            WHERE (
                LOWER(TRIM(c.assigned_pc)) = LOWER(TRIM(%s))
                OR c.build_order_id IN (
                    SELECT id FROM build_orders WHERE LOWER(TRIM(target_pc_name)) = LOWER(TRIM(%s))
                )
            )
            AND (c.status IS NULL OR c.status NOT IN ('Retirado', 'Scrap', 'Stock'))
            AND (c.assigned_pc IS NULL OR c.assigned_pc = '' OR LOWER(TRIM(c.assigned_pc)) = LOWER(TRIM(%s)))
            ORDER BY c.assigned_to_component_id ASC, c.component_type
        ''', (pc_name, pc_name, pc_name)).fetchall()
        
        comp_dicts = [dict(c) for c in pc_components]
        autogenerated_shadow_candidates = find_autogenerated_shadow_components(comp_dicts)
        oc_list = sorted(list({c["oc_number"].strip() for c in comp_dicts if c.get("oc_number") and c["oc_number"].strip()}))
        invoice_list = sorted(list({c["invoice_number"].strip() for c in comp_dicts if c.get("invoice_number") and c["invoice_number"].strip()}))

        available_components = conn.execute('''
            SELECT id, serial_number, component_type, brand_model FROM components 
            WHERE status = 'Stock' AND component_type NOT LIKE 'Bat%'
        ''').fetchall()
        
        baterias_disponibles = conn.execute("SELECT id, serial_number as code, brand_model FROM components WHERE component_type LIKE 'Bat%' AND status = 'Stock'").fetchall()
        
        assigned_network_printers = conn.execute('''
            SELECT np.id, np.ip_address, np.brand_model, np.serial_number FROM network_printers np
            JOIN pc_network_printers pnp ON np.id = pnp.printer_id WHERE pnp.pc_name = %s
        ''', (pc_name,)).fetchall()

        detected_printers = conn.execute('''
            SELECT id, printer_model, printer_port, printer_sn, is_selected
            FROM pc_detected_printers
            WHERE pc_name = %s
              AND is_ignored = 0
              AND printer_model IS NOT NULL
              AND printer_model != ''
              AND printer_model != 'N/A'
              AND UPPER(printer_model) NOT LIKE '%%SIN IMPRESORA%%'
            ORDER BY updated_at DESC
        ''', (pc_name,)).fetchall()
        
        available_network_printers = conn.execute("SELECT id, ip_address, brand_model FROM network_printers ORDER BY ip_address").fetchall()

        disk_summary_lines = _build_disk_summary_lines(pc.get("disk_models"), pc.get("disk_speeds_rpm"))
        hardware_components = _parse_hardware_components(pc)

        monitors_detail, all_unified_components = _enrich_components_with_remitos(conn, pc_components, hardware_components)

        preferred_printer_serial = pc.get("printer_sn")
        preferred_printer_serial_source = "pc"
        if (not preferred_printer_serial or preferred_printer_serial == "N/A") and assigned_network_printers:
            first_assigned = assigned_network_printers[0]
            if first_assigned.get("serial_number") and first_assigned["serial_number"] != "N/A":
                preferred_printer_serial = first_assigned["serial_number"]
                preferred_printer_serial_source = "assigned_network_printer"

        # Buscar Orden de Armado vinculada a esta PC
        linked_bo = None
        try:
            clean_name = pc_name.strip().lower()
            bo_row = conn.execute(
                """
                SELECT DISTINCT bo.id, bo.code, bo.status, bo.target_user, bo.target_fuero, bo.created_at
                FROM build_orders bo
                LEFT JOIN build_order_items boi ON boi.build_order_id = bo.id
                WHERE LOWER(TRIM(bo.target_pc_name)) = %s OR LOWER(TRIM(boi.pc_name)) = %s
                ORDER BY bo.created_at DESC LIMIT 1
                """,
                (clean_name, clean_name)
            ).fetchone()

            if not bo_row:
                bo_row = conn.execute(
                    """
                    SELECT DISTINCT bo.id, bo.code, bo.status, bo.target_user, bo.target_fuero, bo.created_at
                    FROM build_orders bo
                    JOIN components c ON c.build_order_id = bo.id
                    WHERE LOWER(TRIM(c.assigned_pc)) = %s
                    ORDER BY bo.created_at DESC LIMIT 1
                    """,
                    (clean_name,)
                ).fetchone()

            if not bo_row:
                bo_row = conn.execute(
                    """
                    SELECT DISTINCT bo.id, bo.code, bo.status, bo.target_user, bo.target_fuero, bo.created_at
                    FROM build_orders bo
                    JOIN build_order_items boi ON boi.build_order_id = bo.id
                    JOIN components c ON UPPER(TRIM(c.serial_number)) = UPPER(TRIM(boi.serial_number))
                    WHERE LOWER(TRIM(c.assigned_pc)) = %s
                    ORDER BY bo.created_at DESC LIMIT 1
                    """,
                    (clean_name,)
                ).fetchone()

            if bo_row:
                linked_bo = dict(bo_row)

                # Si la PC no tiene last_user o fuero en pcs, enriquecer con los datos de la Orden de Armado
                pc_dict = dict(pc) if pc else {"pc_name": pc_name, "validation_status": "pendiente"}
                if not pc_dict.get("last_user") and linked_bo.get("target_user"):
                    pc_dict["last_user"] = linked_bo["target_user"]
                if not pc_dict.get("fuero") and linked_bo.get("target_fuero"):
                    pc_dict["fuero"] = linked_bo["target_fuero"]
                pc = pc_dict

                # Cargar ítems de la Orden de Armado
                bo_items = conn.execute(
                    """
                    SELECT boi.serial_number, boi.asset_type as component_type, boi.brand_model, boi.pc_name,
                           c.invoice_number, c.oc_number, c.supplier, c.status, c.build_order_id,
                           bo.code as bo_code
                    FROM build_order_items boi
                    LEFT JOIN components c ON c.serial_number = boi.serial_number
                    LEFT JOIN build_orders bo ON bo.id = boi.build_order_id
                    WHERE boi.build_order_id = %s
                    ORDER BY boi.scanned_at ASC
                    """,
                    (linked_bo["id"],)
                ).fetchall()

                existing_sns = {
                    (c.get("serial_number") or "").strip().upper()
                    for c in all_unified_components
                    if _is_real_serial(c.get("serial_number"))
                }
                existing_mon_sns = {
                    (m.get("serial_number") or "").strip().upper()
                    for m in monitors_detail
                    if _is_real_serial(m.get("serial_number"))
                }

                for bi in bo_items:
                    b_dict = dict(bi)
                    sn = b_dict.get("serial_number")
                    sn_key = (sn or "").strip().upper()
                    if _is_real_serial(sn) and sn_key not in existing_sns:
                        existing_sns.add(sn_key)
                        all_unified_components.append(b_dict)
                    
                    comp_type = (b_dict.get("component_type") or "").strip().upper()
                    brand_mod = (b_dict.get("brand_model") or "").strip().upper()
                    if "MONITOR" in comp_type or "MONITOR" in brand_mod:
                        if _is_real_serial(sn) and sn_key not in existing_mon_sns:
                            existing_mon_sns.add(sn_key)
                            monitors_detail.append({
                                "brand_model": b_dict.get("brand_model") or "Monitor Estándar",
                                "serial_number": sn or "Sin S/N",
                                "invoice_number": b_dict.get("invoice_number"),
                                "oc_number": b_dict.get("oc_number"),
                                "supplier": b_dict.get("supplier"),
                                "bo_code": b_dict.get("bo_code"),
                                "status": b_dict.get("status") or "Reservado"
                            })

        except Exception as bo_exc:
            logger.warning("Error buscando/enriqueciendo linked_bo para %s: %s", pc_name, bo_exc)

        display_components, display_monitors_detail = _filter_display_components_for_pc(
            all_unified_components,
            monitors_detail,
            pc_name,
            linked_bo.get("id") if linked_bo else None,
        )

        # Filtrar componentes inyectados por telemetría (script ps1) para la validación estricta
        official_components = [c for c in display_components if c.get("source") != "audit"]
        validation_comparison = get_pc_validation_comparison(pc_name, conn, unified_components=official_components)
        current_status = pc.get("validation_status")
        has_validation_discrepancies = any(
            not item.get("match") for item in (validation_comparison or [])
        )
        has_official_components = bool(official_components)
        effective_status = resolve_effective_validation_status(
            current_status,
            has_official_components,
            has_validation_discrepancies,
        )
        if effective_status != current_status:
            pc = dict(pc)
            pc["validation_status"] = effective_status
            try:
                conn.execute(
                    "UPDATE pcs SET validation_status = %s WHERE pc_name = %s",
                    (effective_status, pc_name)
                )
            except Exception as persist_exc:
                logger.warning(
                    "Error persistiendo el estado de validacion efectivo para %s: %s",
                    pc_name, persist_exc
                )
        build_order_action = resolve_build_order_action(
            effective_status,
            linked_bo,
            has_validation_discrepancies,
            has_official_components,
        )

        # Obtener lista completa de todos los Remitos y OCs existentes en el sistema para autocompletado inteligente
        all_remito_rows = conn.execute("""
            SELECT DISTINCT invoice_number as num FROM components WHERE invoice_number IS NOT NULL AND TRIM(invoice_number) != ''
            UNION
            SELECT DISTINCT invoice_number as num FROM build_orders WHERE invoice_number IS NOT NULL AND TRIM(invoice_number) != ''
            ORDER BY num ASC
        """).fetchall()
        all_existing_remitos = sorted(list({r["num"].strip() for r in all_remito_rows if r.get("num") and r["num"].strip()}))

        all_oc_rows = conn.execute("""
            SELECT DISTINCT oc_number as num FROM components WHERE oc_number IS NOT NULL AND TRIM(oc_number) != ''
            UNION
            SELECT DISTINCT oc_number as num FROM build_orders WHERE oc_number IS NOT NULL AND TRIM(oc_number) != ''
            ORDER BY num ASC
        """).fetchall()
        all_existing_ocs = sorted(list({r["num"].strip() for r in all_oc_rows if r.get("num") and r["num"].strip()}))
        quick_health = _build_quick_health_summary(pc)

        return {
            "pc": pc, "tareas": tareas, "technicians": technicians, "ad_users_list": ad_users_list,
            "audit_logs": audit_logs, "all_pcs": all_pcs, "pc_ups_list": pc_ups_list,
            "available_ups": available_ups, "pc_components": pc_components,
            "all_unified_components": all_unified_components,
            "display_components": display_components,
            "autogenerated_shadow_candidates": autogenerated_shadow_candidates,
            "validation_comparison": validation_comparison,
            "monitors_detail": monitors_detail,
            "display_monitors_detail": display_monitors_detail,
            "available_components": available_components, "baterias_disponibles": baterias_disponibles,
            "sharing_pc": sharing_pc_data, "clients_using_this_printer": clients_using_this_printer,
            "assigned_network_printers": assigned_network_printers,
            "detected_printers": detected_printers,
            "available_network_printers": available_network_printers,
            "disk_summary_lines": disk_summary_lines,
            "hardware_components": hardware_components,
            "preferred_printer_serial": preferred_printer_serial,
            "preferred_printer_serial_source": preferred_printer_serial_source,
            "oc_list": oc_list,
            "invoice_list": invoice_list,
            "all_existing_remitos": all_existing_remitos,
            "all_existing_ocs": all_existing_ocs,
            "quick_health": quick_health,
            "linked_bo": linked_bo,
            "build_order_action": build_order_action,
        }
