
CREATE TABLE IF NOT EXISTS pcs (
    pc_name VARCHAR(255) PRIMARY KEY,
    os_name TEXT,
    processor TEXT,
    ram_gb FLOAT,
    ip_address TEXT,
    last_user TEXT,
    last_report DATETIME,
    ram_detalles TEXT,
    disk_models TEXT,
    disk_speeds_rpm TEXT,
    motherboard_model TEXT,
    monitors TEXT,
    printer_model TEXT,
    printer_port TEXT,
    printer_sn TEXT,
    office_version TEXT,
    ping_ms TEXT,
    ping_loss_pct TEXT,
    alerta_ram_baja TINYINT(1) DEFAULT 0,
    alerta_sin_impresora TINYINT(1) DEFAULT 0,
    alerta_impresora_red TINYINT(1) DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1,
    full_json_data LONGTEXT,
    fuero TEXT,
    switch_name TEXT,
    switch_port TEXT,
    pachera_name TEXT,
    pachera_port TEXT,
    building TEXT,
    floor TEXT,
    alerta_disco TINYINT(1) DEFAULT 0,
    alerta_uptime TINYINT(1) DEFAULT 0,
    alerta_nombre_duplicado TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pc_name VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    descripcion TEXT NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
    solicitante TEXT,
    completed_by TEXT,
    completed_at DATETIME,
    categoria TEXT,
    assigned_to TEXT,
    fuero TEXT,
    tipo_actividad VARCHAR(50) DEFAULT 'tarea',
    prioridad INT DEFAULT 1,
    impacto_valor INT DEFAULT 1,
    resumen_impacto TEXT,
    solucion TEXT,
    is_edited TINYINT(1) DEFAULT 0,
    desc_edited TINYINT(1) DEFAULT 0,
    sol_edited TINYINT(1) DEFAULT 0,
    FOREIGN KEY (pc_name) REFERENCES pcs(pc_name) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pc_detected_printers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pc_name VARCHAR(255),
    printer_model TEXT,
    printer_port TEXT,
    printer_sn TEXT,
    is_ignored TINYINT(1) DEFAULT 0,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (pc_name) REFERENCES pcs(pc_name) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS technicians (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS components (
    id INT AUTO_INCREMENT PRIMARY KEY,
    serial_number VARCHAR(255) UNIQUE,
    component_type VARCHAR(100) NOT NULL,
    brand_model TEXT,
    status VARCHAR(50) DEFAULT 'Stock',
    assigned_pc VARCHAR(255),
    assigned_to_component_id INT,
    assigned_fuero VARCHAR(255) DEFAULT NULL,
    assigned_user VARCHAR(255) DEFAULT NULL,
    supplier TEXT,
    invoice_number TEXT,
    oc_number VARCHAR(100) DEFAULT NULL,
    is_autogenerated_id TINYINT(1) DEFAULT 0,
    kit_name VARCHAR(255) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (assigned_pc) REFERENCES pcs(pc_name) ON DELETE SET NULL,
    FOREIGN KEY (assigned_to_component_id) REFERENCES components(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_catalogs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    item_value VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_cat_val (category, item_value)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pc_name VARCHAR(255),
    field VARCHAR(255),
    old_value TEXT,
    new_value TEXT,
    user_name VARCHAR(255) DEFAULT 'SISTEMA',
    action_type VARCHAR(100) DEFAULT 'UPDATE',
    ip_address VARCHAR(100),
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ups_inventory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(255) UNIQUE NOT NULL,
    model VARCHAR(255) DEFAULT 'LYONN CTB-800V',
    supplier TEXT,
    invoice_number TEXT,
    assigned_pc VARCHAR(255),
    assigned_battery_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (assigned_pc) REFERENCES pcs(pc_name) ON DELETE SET NULL,
    FOREIGN KEY (assigned_battery_id) REFERENCES components(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ad_users (
    username VARCHAR(255) PRIMARY KEY,
    real_name TEXT,
    phone TEXT,
    fuero TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fuero_mappings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    prefix_code VARCHAR(100) NOT NULL UNIQUE,
    fuero_label VARCHAR(255) NOT NULL,
    notes TEXT,
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title TEXT,
    body TEXT,
    url TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    read_at DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tech_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    technician_name VARCHAR(100),
    sender VARCHAR(100) DEFAULT 'Sistema',
    task_id INT DEFAULT NULL,
    msg_type VARCHAR(50) DEFAULT 'direct',
    title TEXT,
    body TEXT,
    url TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    read_at DATETIME DEFAULT NULL,
    scheduled_for DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    role VARCHAR(50) DEFAULT 'tecnico',
    technician_name VARCHAR(255),
    password_hash TEXT NOT NULL,
    is_superuser TINYINT(1) DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1,
    must_change_password TINYINT(1) DEFAULT 0,
    can_access_dashboard TINYINT(1) DEFAULT 1,
    can_access_mobile TINYINT(1) DEFAULT 1,
    can_access_infrastructure TINYINT(1) DEFAULT 0,
    can_access_reports TINYINT(1) DEFAULT 0,
    can_audit_racks TINYINT(1) DEFAULT 0,
    can_manage_stock TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS racks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    ubicacion VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rack_audits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rack_id INT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    estado_luces_bool TINYINT(1) DEFAULT 1,
    limpieza_ok_bool TINYINT(1) DEFAULT 1,
    iluminacion_ok_bool TINYINT(1) DEFAULT 1,
    temperatura_celsius_float FLOAT,
    observaciones_text TEXT,
    ruta_foto_text TEXT,
    tecnico VARCHAR(255),
    FOREIGN KEY (rack_id) REFERENCES racks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS switches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo_qr VARCHAR(100) UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    edificio VARCHAR(100),
    lugar VARCHAR(100),
    puertos_totales INT DEFAULT 0,
    puertos_poe INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS switch_audits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    switch_id INT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    estado_general VARCHAR(50) DEFAULT 'Online',
    puertos_libres INT DEFAULT 0,
    puertos_ocupados INT DEFAULT 0,
    puertos_fallados INT DEFAULT 0,
    observaciones_text TEXT,
    tecnico VARCHAR(255),
    FOREIGN KEY (switch_id) REFERENCES switches(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scan_sessions (
    session_id VARCHAR(32) PRIMARY KEY,
    created_at DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    barcodes LONGTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO racks (nombre, ubicacion) VALUES ('Rack Central', '');
INSERT IGNORE INTO racks (nombre, ubicacion) VALUES ('Piso 1', '');
INSERT IGNORE INTO racks (nombre, ubicacion) VALUES ('Piso 2', '');
INSERT IGNORE INTO racks (nombre, ubicacion) VALUES ('Backup', '');
INSERT IGNORE INTO racks (nombre, ubicacion) VALUES ('Familia', '');
INSERT IGNORE INTO racks (nombre, ubicacion) VALUES ('Residual', '');
INSERT IGNORE INTO racks (nombre, ubicacion) VALUES ('Biblioteca', '');

INSERT IGNORE INTO stock_catalogs (category, item_value) VALUES 
('supplier', 'NOVA'), ('supplier', 'BGH'), ('supplier', 'Banghó'),
('supplier', 'EXO'), ('supplier', 'HP'), ('supplier', 'Dell'),
('supplier', 'Lenovo'), ('supplier', 'Kelyx'),
('type', 'Monitor'), ('type', 'Teclado'), ('type', 'Mouse'),
('type', 'CPU'), ('type', 'UPS'), ('type', 'Impresora'),
('type', 'Disco'), ('type', 'Memoria'), ('type', 'Fuente'),
('type', 'Gabinete'), ('type', 'Otro');

INSERT IGNORE INTO fuero_mappings (prefix_code, fuero_label, is_active) VALUES
('CIV1', 'Civil y Comercial 1', 1),
('CIV2', 'Civil y Comercial 2', 1),
('CIV3', 'Civil y Comercial 3', 1),
('CIV4', 'Civil y Comercial 4', 1),
('DEF1', 'Defensoria 1', 1),
('DEF2', 'Defensoria 2', 1),
('DEF3', 'Defensoria 3', 1),
('DEF4', 'Defensoria 4', 1),
('PEN1', 'Penal 1', 1),
('PEN2', 'Penal 2', 1),
('PEN3', 'Penal 3', 1),
('PEN4', 'Penal 4', 1);
