<script lang="ts">
	import { resolve } from '$app/paths';

	let { data } = $props();

	const summaryCards = $derived([
		{ label: 'Componentes', value: data.summary.total },
		{ label: 'Disponibles', value: data.summary.available },
		{ label: 'Asignados', value: data.summary.assigned },
		{ label: 'Reservados', value: data.summary.reserved },
		{ label: 'Retirados', value: data.summary.retired }
	]);

	function formatDate(value: string) {
		if (!value) return '';
		const date = new Date(value);
		if (Number.isNaN(date.getTime())) return value;
		return new Intl.DateTimeFormat('es-AR', { dateStyle: 'short' }).format(date);
	}

	function assignmentFor(component: (typeof data.components)[number]) {
		const target = [component.assignedPc, component.assignedUser, component.assignedFuero]
			.filter(Boolean)
			.join(' - ');
		if (target) return target;
		if (component.buildOrderId) return `Orden de armado #${component.buildOrderId}`;
		return 'Sin asignacion';
	}
</script>

<svelte:head>
	<title>Stock - Inventario Next</title>
</svelte:head>

<main class="stock-shell">
	<a class="back-link" href={resolve('/')}>Inventario Next</a>

	<header class="page-header">
		<div>
			<p class="eyebrow">Patrimonio y remitos</p>
			<h1>Stock</h1>
			<p class="subtitle">Lectura de componentes por estado patrimonial, remito, OC y destino.</p>
		</div>
		<div class="mode" data-mode={data.mode}>
			<span>Origen</span>
			<strong>{data.mode}</strong>
		</div>
	</header>

	<section class="summary-grid" aria-label="Resumen de stock">
		{#each summaryCards as item (item.label)}
			<div>
				<strong>{item.value}</strong>
				<span>{item.label}</span>
			</div>
		{/each}
	</section>

	<form class="filters" method="GET" action={resolve('/stock')}>
		<label>
			<span>Buscar</span>
			<input
				name="q"
				type="search"
				value={data.query}
				placeholder="Serial, remito, OC, modelo, usuario"
				autocomplete="off"
			/>
		</label>
		<label>
			<span>Estado</span>
			<select name="estado" value={data.state}>
				{#each data.states as state (state.value || 'todos')}
					<option value={state.value}>{state.label}</option>
				{/each}
			</select>
		</label>
		<label>
			<span>Tipo</span>
			<select name="tipo" value={data.type}>
				<option value="">Todos</option>
				{#each data.types as type (type)}
					<option value={type}>{type}</option>
				{/each}
			</select>
		</label>
		<button type="submit">Filtrar</button>
	</form>

	<p class="note">{data.note}</p>

	<section class="stock-list" aria-label="Listado de componentes">
		{#if data.components.length}
			{#each data.components as component (component.id)}
				<article class="stock-row" data-state={component.state}>
					<div class="asset">
						<strong>{component.componentType}</strong>
						<span>{component.brandModel || 'Sin modelo'}</span>
						<em>{component.serialNumber || 'Sin serial'}</em>
					</div>
					<div class="origin">
						<span>Remito {component.invoiceNumber || 'N/D'}</span>
						<span>OC {component.ocNumber || 'N/D'}</span>
						<span>{component.supplier || 'Sin proveedor'}</span>
					</div>
					<div class="assignment">
						<strong>{component.state}</strong>
						<span>{assignmentFor(component)}</span>
						{#if component.patrimonyCode}
							<em>Patrimonio {component.patrimonyCode}</em>
						{/if}
					</div>
					<div class="meta">
						<span>{component.status || 'Sin estado'}</span>
						<span>{component.lifecycleStatus || 'Sin ciclo'}</span>
						{#if component.createdAt}
							<time datetime={component.createdAt}>{formatDate(component.createdAt)}</time>
						{/if}
						{#if component.isAutogeneratedId}
							<em>Auto-ID</em>
						{/if}
					</div>
				</article>
			{/each}
		{:else}
			<p class="empty">No hay componentes para ese criterio.</p>
		{/if}
	</section>
</main>

<style>
	:global(body) {
		margin: 0;
		background: #0e1116;
		color: #eef2f7;
		font-family:
			Inter,
			ui-sans-serif,
			system-ui,
			-apple-system,
			BlinkMacSystemFont,
			'Segoe UI',
			sans-serif;
	}

	.stock-shell {
		min-height: 100vh;
		box-sizing: border-box;
		padding: 28px;
		background:
			linear-gradient(90deg, rgba(24, 60, 81, 0.2) 1px, transparent 1px),
			linear-gradient(0deg, rgba(24, 60, 81, 0.18) 1px, transparent 1px), #0e1116;
		background-size: 44px 44px;
	}

	.back-link {
		color: #81d8d0;
		font-weight: 700;
		text-decoration: none;
	}

	.page-header {
		display: flex;
		align-items: flex-start;
		justify-content: space-between;
		gap: 24px;
		margin-top: 20px;
		padding-bottom: 22px;
		border-bottom: 1px solid #253140;
	}

	.eyebrow {
		margin: 0 0 8px;
		color: #81d8d0;
		font-size: 0.78rem;
		font-weight: 700;
		text-transform: uppercase;
	}

	h1,
	p {
		margin: 0;
	}

	h1 {
		font-size: clamp(2rem, 6vw, 4rem);
		line-height: 1;
	}

	.subtitle,
	.note,
	.empty,
	.mode span,
	.summary-grid span,
	.asset span,
	.asset em,
	.origin span,
	.assignment span,
	.assignment em,
	.meta span,
	.meta time,
	.meta em {
		color: #9aa8b8;
	}

	.subtitle {
		margin-top: 10px;
	}

	.mode {
		display: grid;
		gap: 4px;
		min-width: 140px;
		padding: 12px 14px;
		border: 1px solid #354356;
		background: rgba(10, 14, 20, 0.82);
		border-radius: 6px;
		text-align: right;
	}

	.mode strong {
		text-transform: uppercase;
	}

	.summary-grid {
		display: grid;
		grid-template-columns: repeat(5, minmax(0, 1fr));
		gap: 12px;
		margin: 22px 0;
	}

	.summary-grid div,
	.stock-row,
	.empty {
		border: 1px solid #253140;
		background: rgba(16, 22, 30, 0.94);
		border-radius: 6px;
	}

	.summary-grid div {
		padding: 16px;
	}

	.summary-grid strong,
	.summary-grid span,
	.asset strong,
	.asset span,
	.asset em,
	.origin span,
	.assignment strong,
	.assignment span,
	.assignment em,
	.meta span,
	.meta time,
	.meta em {
		display: block;
	}

	.summary-grid strong {
		font-size: 2rem;
		line-height: 1;
	}

	.summary-grid span {
		margin-top: 8px;
	}

	.filters {
		display: grid;
		grid-template-columns: minmax(220px, 1fr) minmax(140px, 190px) minmax(150px, 220px) auto;
		gap: 10px;
		align-items: end;
		max-width: 1060px;
		margin-bottom: 14px;
	}

	.filters label span {
		display: block;
		margin-bottom: 8px;
		color: #c5d0dd;
		font-weight: 700;
	}

	.filters input,
	.filters select,
	.filters button {
		width: 100%;
		box-sizing: border-box;
		border-radius: 6px;
		font: inherit;
	}

	.filters input,
	.filters select {
		padding: 11px 12px;
		border: 1px solid #354356;
		background: #0a0e14;
		color: #eef2f7;
	}

	.filters button {
		padding: 11px 16px;
		border: 1px solid #81d8d0;
		background: #81d8d0;
		color: #071012;
		font-weight: 800;
	}

	.note {
		margin-bottom: 16px;
	}

	.stock-list {
		display: grid;
		gap: 10px;
	}

	.stock-row {
		display: grid;
		grid-template-columns: minmax(220px, 1.1fr) minmax(180px, 0.8fr) minmax(220px, 1fr) minmax(
				130px,
				0.55fr
			);
		gap: 18px;
		padding: 14px 16px;
	}

	.asset span,
	.asset em,
	.origin span + span,
	.assignment span,
	.assignment em,
	.meta span + span,
	.meta time,
	.meta em {
		margin-top: 4px;
	}

	.asset em,
	.assignment em,
	.meta em {
		font-style: normal;
	}

	.assignment strong {
		color: #f5c451;
		text-transform: capitalize;
	}

	.stock-row[data-state='disponible'] .assignment strong {
		color: #81d8d0;
	}

	.stock-row[data-state='retirado'] .assignment strong {
		color: #ff8a7a;
	}

	.empty {
		padding: 20px;
	}

	@media (max-width: 1100px) {
		.summary-grid {
			grid-template-columns: repeat(3, minmax(0, 1fr));
		}

		.filters,
		.stock-row {
			grid-template-columns: 1fr 1fr;
		}
	}

	@media (max-width: 680px) {
		.stock-shell {
			padding: 18px;
		}

		.page-header,
		.filters,
		.stock-row {
			display: grid;
			grid-template-columns: 1fr;
		}

		.summary-grid {
			grid-template-columns: 1fr;
		}

		.mode {
			width: fit-content;
			text-align: left;
		}
	}
</style>
