import { appConfig } from './config';
import { getMysqlPool } from './db';
import type { RowDataPacket } from 'mysql2';

export type StockState = 'disponible' | 'reservado' | 'asignado' | 'retirado' | 'otro';

export interface StockStateSeed {
	status: string;
	lifecycleStatus: string;
	assignedPc: string;
	assignedUser: string;
	assignedFuero: string;
	buildOrderId: number | null;
}

export interface StockComponent extends StockStateSeed {
	id: number;
	serialNumber: string;
	componentType: string;
	brandModel: string;
	supplier: string;
	invoiceNumber: string;
	ocNumber: string;
	kitName: string;
	patrimonyCode: string;
	createdAt: string;
	state: StockState;
	isAutogeneratedId: boolean;
}

export interface StockBoard {
	mode: 'demo' | 'mysql';
	query: string;
	state: string;
	type: string;
	components: StockComponent[];
	types: string[];
	states: Array<{ value: StockState | ''; label: string }>;
	summary: {
		total: number;
		available: number;
		assigned: number;
		reserved: number;
		retired: number;
	};
	note: string;
}

interface ComponentRow extends RowDataPacket {
	id: number;
	serial_number?: string | null;
	component_type?: string | null;
	brand_model?: string | null;
	status?: string | null;
	lifecycle_status?: string | null;
	assigned_pc?: string | null;
	assigned_user?: string | null;
	assigned_fuero?: string | null;
	supplier?: string | null;
	invoice_number?: string | null;
	oc_number?: string | null;
	kit_name?: string | null;
	patrimonio_code?: string | null;
	created_at?: Date | string | null;
	build_order_id?: number | null;
	is_autogenerated_id?: number | null;
}

const STOCK_STATES: StockBoard['states'] = [
	{ value: '', label: 'Todos' },
	{ value: 'disponible', label: 'Disponible' },
	{ value: 'reservado', label: 'Reservado' },
	{ value: 'asignado', label: 'Asignado' },
	{ value: 'retirado', label: 'Retirado' },
	{ value: 'otro', label: 'Otro' }
];

function normalize(value: string) {
	return value
		.trim()
		.toLowerCase()
		.normalize('NFD')
		.replace(/\p{Diacritic}/gu, '');
}

function dateToIso(value: Date | string | null | undefined) {
	if (!value) return '';
	const date = new Date(value);
	return Number.isNaN(date.getTime()) ? String(value) : date.toISOString();
}

function hasValue(value: string | null | undefined) {
	const normalized = normalize(String(value ?? ''));
	return Boolean(
		normalized && !['stock', 'disponible', 'none', 'null', 'sin asignar'].includes(normalized)
	);
}

export function stockStateForComponent(component: StockStateSeed): StockState {
	const status = normalize(component.status);
	const lifecycle = normalize(component.lifecycleStatus);
	const isAssigned =
		hasValue(component.assignedPc) ||
		hasValue(component.assignedUser) ||
		hasValue(component.assignedFuero);

	if (
		lifecycle === 'retirado' ||
		lifecycle === 'scrap' ||
		status === 'retirado' ||
		status === 'scrap'
	) {
		return 'retirado';
	}

	if (component.buildOrderId || lifecycle === 'en_armado' || status === 'reservado') {
		return 'reservado';
	}

	if (isAssigned || lifecycle === 'desplegado' || status === 'installed' || status === 'asignado') {
		return 'asignado';
	}

	if (lifecycle === 'stock' || status === 'stock') {
		return 'disponible';
	}

	return 'otro';
}

function rowToComponent(row: ComponentRow): StockComponent {
	const seed: StockStateSeed = {
		status: row.status ?? '',
		lifecycleStatus: row.lifecycle_status ?? '',
		assignedPc: row.assigned_pc ?? '',
		assignedUser: row.assigned_user ?? '',
		assignedFuero: row.assigned_fuero ?? '',
		buildOrderId: row.build_order_id ?? null
	};
	const serialNumber = row.serial_number ?? '';

	return {
		id: row.id,
		serialNumber,
		componentType: row.component_type ?? 'Sin tipo',
		brandModel: row.brand_model ?? '',
		supplier: row.supplier ?? '',
		invoiceNumber: row.invoice_number ?? '',
		ocNumber: row.oc_number ?? '',
		kitName: row.kit_name ?? '',
		patrimonyCode: row.patrimonio_code ?? '',
		createdAt: dateToIso(row.created_at),
		isAutogeneratedId:
			Boolean(row.is_autogenerated_id) || serialNumber.toUpperCase().startsWith('INT-'),
		...seed,
		state: stockStateForComponent(seed)
	};
}

function filterComponents(
	components: StockComponent[],
	query: string,
	state: string,
	type: string
) {
	const normalizedQuery = normalize(query);
	const normalizedType = normalize(type);
	return components.filter((component) => {
		const queryMatch =
			!normalizedQuery ||
			normalize(
				`${component.serialNumber} ${component.componentType} ${component.brandModel} ${component.supplier} ${component.invoiceNumber} ${component.ocNumber} ${component.assignedPc} ${component.assignedUser} ${component.assignedFuero} ${component.kitName} ${component.patrimonyCode}`
			).includes(normalizedQuery);
		const stateMatch = !state || component.state === state;
		const typeMatch = !normalizedType || normalize(component.componentType) === normalizedType;
		return queryMatch && stateMatch && typeMatch;
	});
}

function summarize(components: StockComponent[]) {
	return {
		total: components.length,
		available: components.filter((component) => component.state === 'disponible').length,
		assigned: components.filter((component) => component.state === 'asignado').length,
		reserved: components.filter((component) => component.state === 'reservado').length,
		retired: components.filter((component) => component.state === 'retirado').length
	};
}

function typesFromComponents(components: StockComponent[]) {
	return Array.from(
		new Set(components.map((component) => component.componentType).filter(Boolean))
	).sort((left, right) => left.localeCompare(right, 'es'));
}

export function demoStockBoard({
	query = '',
	state = '',
	type = ''
}: {
	query?: string;
	state?: string;
	type?: string;
} = {}): StockBoard {
	const allComponents = [
		rowToComponent({
			id: 1,
			serial_number: 'MON-2026-001',
			component_type: 'Monitor',
			brand_model: 'Samsung 24"',
			status: 'Stock',
			lifecycle_status: 'stock',
			supplier: 'NOVA',
			invoice_number: 'REM-001',
			oc_number: 'OC-185-2026',
			created_at: '2026-08-20T12:00:00.000Z'
		} as ComponentRow),
		rowToComponent({
			id: 2,
			serial_number: 'CPU-2026-009',
			component_type: 'CPU',
			brand_model: 'Lenovo ThinkCentre',
			status: 'Installed',
			lifecycle_status: 'desplegado',
			assigned_pc: 'JCC1-PC01',
			assigned_user: 'Gustavo Mock AD',
			assigned_fuero: 'Sistemas',
			supplier: 'Lenovo',
			invoice_number: 'REM-001',
			oc_number: 'OC-185-2026',
			created_at: '2026-08-19T12:00:00.000Z'
		} as ComponentRow),
		rowToComponent({
			id: 3,
			serial_number: 'INT-TEC-20260821-1234',
			component_type: 'Teclado',
			brand_model: 'Logitech K120',
			status: 'Reservado',
			lifecycle_status: 'en_armado',
			build_order_id: 4,
			supplier: 'Stock interno',
			created_at: '2026-08-21T12:00:00.000Z'
		} as ComponentRow),
		rowToComponent({
			id: 4,
			serial_number: 'HDD-OLD-77',
			component_type: 'Disco',
			brand_model: 'WD Blue 1TB',
			status: 'Retirado',
			lifecycle_status: 'retirado',
			created_at: '2026-08-10T12:00:00.000Z'
		} as ComponentRow)
	];
	const components = filterComponents(allComponents, query, state, type);

	return {
		mode: 'demo',
		query,
		state,
		type,
		components,
		types: typesFromComponents(allComponents),
		states: STOCK_STATES,
		summary: summarize(components),
		note: 'Sin .env local: stock demo, no se consulto MySQL.'
	};
}

export async function loadStockBoard({
	query = '',
	state = '',
	type = '',
	limit = 120
}: {
	query?: string;
	state?: string;
	type?: string;
	limit?: number;
} = {}): Promise<StockBoard> {
	const trimmedQuery = query.trim();
	const trimmedState = state.trim() as StockState | '';
	const trimmedType = type.trim();
	if (!appConfig.MYSQL_PASSWORD)
		return demoStockBoard({ query: trimmedQuery, state: trimmedState, type: trimmedType });

	const pool = getMysqlPool();
	const likeQuery = `%${trimmedQuery}%`;
	const [rows] = await pool.query<ComponentRow[]>(
		`
		SELECT
			id, serial_number, component_type, brand_model, status, lifecycle_status,
			assigned_pc, assigned_user, assigned_fuero, supplier, invoice_number,
			oc_number, kit_name, patrimonio_code, created_at, build_order_id,
			is_autogenerated_id
		FROM components
		WHERE (? = '' OR component_type = ?)
		  AND (
			? = ''
			OR serial_number LIKE ?
			OR component_type LIKE ?
			OR brand_model LIKE ?
			OR supplier LIKE ?
			OR invoice_number LIKE ?
			OR oc_number LIKE ?
			OR assigned_pc LIKE ?
			OR assigned_user LIKE ?
			OR assigned_fuero LIKE ?
			OR kit_name LIKE ?
			OR patrimonio_code LIKE ?
		  )
		ORDER BY created_at DESC, component_type ASC, brand_model ASC
		LIMIT ?
		`,
		[
			trimmedType,
			trimmedType,
			trimmedQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			likeQuery,
			limit * 3
		]
	);
	const allComponents = rows.map(rowToComponent);
	const components = filterComponents(allComponents, '', trimmedState, '').slice(0, limit);

	return {
		mode: 'mysql',
		query: trimmedQuery,
		state: trimmedState,
		type: trimmedType,
		components,
		types: typesFromComponents(allComponents),
		states: STOCK_STATES,
		summary: summarize(components),
		note: appConfig.MYSQL_READ_ONLY
			? 'MySQL conectado en modo lectura.'
			: 'MySQL conectado con escritura habilitada por configuracion.'
	};
}
