spring.application.name=Inventario Modular
spring.profiles.default=local
inventario.version=${INVENTARIO_VERSION:0.0.1-SNAPSHOT}
inventario.local-auth.enabled=${INVENTARIO_LOCAL_AUTH_ENABLED:false}
inventario.local-db-auth.enabled=${INVENTARIO_LOCAL_DB_AUTH_ENABLED:false}
spring.flyway.validate-on-migrate=false
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update
