CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(120) NOT NULL UNIQUE,
  nombre_visible VARCHAR(180) NOT NULL,
  fuero VARCHAR(120) NOT NULL,
  origen VARCHAR(20) NOT NULL DEFAULT 'AD',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE modulos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  orden INT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE permisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NOT NULL
);

CREATE TABLE usuario_roles (
  usuario_id BIGINT NOT NULL,
  rol_id BIGINT NOT NULL,
  PRIMARY KEY (usuario_id, rol_id)
);

CREATE TABLE rol_modulo_permisos (
  rol_id BIGINT NOT NULL,
  modulo_id BIGINT NOT NULL,
  permiso_id BIGINT NOT NULL,
  PRIMARY KEY (rol_id, modulo_id, permiso_id)
);

CREATE TABLE credenciales_locales (
  usuario_id BIGINT PRIMARY KEY,
  password_hash VARCHAR(255) NOT NULL,
  requiere_cambio_clave BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE equipos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  ultimo_usuario VARCHAR(120),
  fuero VARCHAR(120) NOT NULL,
  ubicacion VARCHAR(180),
  ip VARCHAR(45),
  sistema_operativo VARCHAR(180),
  procesador VARCHAR(255),
  ram_mb INT,
  ram_detalles VARCHAR(500),
  ram_seriales VARCHAR(500),
  discos_modelos VARCHAR(500),
  discos_seriales VARCHAR(500),
  motherboard_modelo VARCHAR(255),
  motherboard_serial VARCHAR(255),
  monitores VARCHAR(500),
  teclado VARCHAR(180),
  mouse VARCHAR(180),
  impresora VARCHAR(180),
  monitoreo VARCHAR(60) NOT NULL DEFAULT 'SIN_REPORTE',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  ultimo_reporte_en TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE componentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_id BIGINT NOT NULL,
  tipo VARCHAR(60) NOT NULL,
  origen VARCHAR(40) NOT NULL,
  estado_comparacion VARCHAR(40) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  marca VARCHAR(120),
  modelo VARCHAR(180),
  serial VARCHAR(180),
  capacidad VARCHAR(120),
  ubicacion VARCHAR(120),
  observaciones VARCHAR(500),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stock_componentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(60) NOT NULL,
  estado VARCHAR(40) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  marca VARCHAR(120),
  modelo VARCHAR(180),
  serial VARCHAR(180),
  capacidad VARCHAR(120),
  ubicacion VARCHAR(120),
  observaciones VARCHAR(500),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ordenes_armado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_id BIGINT NOT NULL,
  estado VARCHAR(40) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  observaciones VARCHAR(500),
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orden_armado_componentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_id BIGINT NOT NULL,
  componente_id BIGINT NOT NULL,
  stock_componente_id BIGINT,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auditoria_eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario VARCHAR(120) NOT NULL,
  modulo VARCHAR(60) NOT NULL,
  accion VARCHAR(80) NOT NULL,
  entidad_tipo VARCHAR(80) NOT NULL,
  entidad_id BIGINT,
  detalle VARCHAR(1000) NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tareas_tecnicas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_id BIGINT,
  titulo VARCHAR(180) NOT NULL,
  descripcion VARCHAR(1000),
  estado VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE',
  prioridad VARCHAR(40) NOT NULL DEFAULT 'MEDIA',
  responsable VARCHAR(120),
  observaciones_cierre VARCHAR(1000),
  cerrado_en TIMESTAMP,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE muebles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(80) NOT NULL UNIQUE,
  tipo VARCHAR(80) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  ubicacion VARCHAR(180),
  fuero VARCHAR(120),
  responsable VARCHAR(120),
  estado VARCHAR(40) NOT NULL DEFAULT 'ACTIVO',
  observaciones VARCHAR(500),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bienes_patrimoniales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_patrimonial VARCHAR(80) NOT NULL UNIQUE,
  categoria VARCHAR(80) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  ubicacion VARCHAR(180),
  fuero VARCHAR(120),
  custodio VARCHAR(120),
  estado VARCHAR(40) NOT NULL DEFAULT 'EN_USO',
  equipo_id BIGINT,
  observaciones VARCHAR(500),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE actas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(80) NOT NULL UNIQUE,
  tipo VARCHAR(40) NOT NULL DEFAULT 'ENTREGA',
  equipo_id BIGINT,
  fecha_emision DATE,
  destinatario VARCHAR(180) NOT NULL,
  responsable_entrega VARCHAR(120),
  responsable_recepcion VARCHAR(120),
  detalle VARCHAR(1000) NOT NULL,
  estado VARCHAR(40) NOT NULL DEFAULT 'BORRADOR',
  observaciones VARCHAR(500),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ubicaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(80) NOT NULL UNIQUE,
  nombre VARCHAR(180) NOT NULL,
  tipo VARCHAR(40) NOT NULL DEFAULT 'OFICINA',
  fuero VARCHAR(120),
  responsable VARCHAR(120),
  edificio VARCHAR(120),
  piso VARCHAR(40),
  estado VARCHAR(40) NOT NULL DEFAULT 'ACTIVA',
  observaciones VARCHAR(500),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO usuarios (id, username, nombre_visible, fuero, origen, activo)
VALUES
  (1, 'admin.local', 'Administrador Local', 'Desarrollo local', 'LOCAL', TRUE),
  (2, 'sin.permisos', 'Usuario Sin Permisos', 'Mesa de ayuda', 'AD', FALSE);

INSERT INTO roles (id, codigo, nombre, descripcion, activo)
VALUES (1, 'ADMINISTRADOR', 'Administrador', 'Acceso total a los modulos del sistema.', TRUE);

INSERT INTO modulos (id, codigo, nombre, descripcion, orden, activo)
VALUES
  (1, 'EQUIPOS', 'Equipos', 'Inventario tecnico de computadoras y dispositivos principales.', 10, TRUE),
  (2, 'USUARIOS', 'Usuarios', 'Administracion de usuarios, roles, permisos y modulos.', 70, TRUE),
  (3, 'COMPONENTES', 'Componentes', 'Partes, repuestos y componentes asociados a equipos.', 60, TRUE),
  (4, 'STOCK', 'Stock', 'Componentes sueltos disponibles para armado, mejora o reemplazo.', 50, TRUE),
  (5, 'ORDENES_ARMADO', 'Ordenes de Armado', 'Planificacion de equipos nuevos o mejoras con componentes esperados.', 55, TRUE),
  (6, 'AUDITORIA', 'Auditoria', 'Eventos de cambios relevantes del sistema.', 95, TRUE),
  (7, 'MUEBLES', 'Muebles', 'Gestion fisica de muebles y bienes de oficina.', 30, TRUE),
  (8, 'PATRIMONIO', 'Patrimonio', 'Control patrimonial institucional y reportes administrativos.', 40, TRUE),
  (9, 'TAREAS', 'Tareas', 'Seguimiento de tareas tecnicas y operativas.', 90, TRUE),
  (10, 'REPORTES', 'Reportes', 'Consultas, listados y exportaciones del sistema.', 80, TRUE),
  (11, 'ACTAS', 'Actas', 'Gestion de actas y constancias asociadas al inventario.', 20, TRUE),
  (12, 'UBICACIONES', 'Ubicaciones', 'Oficinas, depositos, salas y racks vinculados al inventario.', 25, TRUE);

INSERT INTO permisos (id, codigo, nombre, descripcion)
VALUES
  (1, 'VER', 'Ver', 'Permite consultar informacion del modulo.'),
  (2, 'ADMINISTRAR', 'Administrar', 'Permite administrar configuracion del modulo.'),
  (3, 'EDITAR', 'Editar', 'Permite modificar registros existentes.'),
  (4, 'EXPORTAR', 'Exportar', 'Permite exportar informacion del modulo.');

INSERT INTO usuario_roles (usuario_id, rol_id)
VALUES (1, 1);

INSERT INTO rol_modulo_permisos (rol_id, modulo_id, permiso_id)
VALUES
  (1, 1, 1),
  (1, 1, 2),
  (1, 1, 3),
  (1, 2, 1),
  (1, 2, 2),
  (1, 3, 1),
  (1, 3, 2),
  (1, 3, 3),
  (1, 4, 1),
  (1, 4, 2),
  (1, 4, 3),
  (1, 5, 1),
  (1, 5, 2),
  (1, 5, 3),
  (1, 6, 1),
  (1, 6, 2),
  (1, 7, 1),
  (1, 7, 2),
  (1, 7, 3),
  (1, 8, 1),
  (1, 8, 2),
  (1, 8, 3),
  (1, 9, 1),
  (1, 9, 2),
  (1, 9, 3),
  (1, 10, 1),
  (1, 10, 2),
  (1, 10, 4),
  (1, 11, 1),
  (1, 11, 2),
  (1, 11, 3),
  (1, 12, 1),
  (1, 12, 2),
  (1, 12, 3);

INSERT INTO equipos (
  id, nombre, ultimo_usuario, fuero, ubicacion, ip, sistema_operativo, procesador, ram_mb,
  ram_detalles, ram_seriales, discos_modelos, discos_seriales, motherboard_modelo,
  motherboard_serial, monitores, teclado, mouse, impresora, monitoreo, activo)
VALUES
  (1, 'PC-INF-001', 'gmurad', 'Informatica', 'Oficina Informatica', '10.15.2.10', 'Windows 11 Pro', 'Intel Core i5', 16384,
   '2x8GB DDR4', 'RAMSN-001 | RAMSN-002', 'KINGSTON SA400', 'DISK-001', 'Dell 0ABC',
   'MB-001', 'Dell 22 SN MON-001', 'Logitech Keyboard', 'Logitech Mouse', 'HP LaserJet', 'REPORTADO', TRUE),
  (2, 'PC-MESA-002', 'mesa.entrada', 'Mesa de ayuda', NULL, '10.15.2.11', 'Windows 10 Pro', 'Intel Core i3', 8192,
   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'REPORTADO', TRUE);

INSERT INTO componentes (
  id, equipo_id, tipo, origen, estado_comparacion, descripcion, marca, modelo,
  serial, capacidad, ubicacion, observaciones, activo)
VALUES
  (1, 1, 'RAM', 'SCRIPT', 'COINCIDE', 'Modulo RAM instalado', 'Kingston', 'DDR4 2666', 'RAMSN-001', '8GB', 'Slot 1', 'Detectado por script', TRUE),
  (2, 1, 'DISCO', 'ORDEN_ARMADO', 'ESPERADO', 'Disco esperado por orden de armado', 'Kingston', 'SA400', 'DISK-001', '480GB', 'SATA 1', 'Debe coincidir con el reporte', TRUE);

INSERT INTO stock_componentes (
  id, tipo, estado, descripcion, marca, modelo, serial, capacidad, ubicacion, observaciones, activo)
VALUES
  (1, 'RAM', 'DISPONIBLE', 'Memoria RAM nueva para armado', 'Kingston', 'DDR4 2666', 'STOCK-RAM-001', '8GB', 'Deposito Informatica', 'Disponible para orden de armado', TRUE);

INSERT INTO tareas_tecnicas (id, equipo_id, titulo, descripcion, estado, prioridad, responsable)
VALUES (1, 1, 'Revisar mantenimiento preventivo', 'Tarea seed para reportes.', 'PENDIENTE', 'MEDIA', 'admin.local');

INSERT INTO muebles (id, codigo, tipo, descripcion, ubicacion, fuero, responsable, estado, observaciones, activo)
VALUES (1, 'MUE-SEED-001', 'SILLA', 'Silla operativa de Informatica', 'Informatica', 'Informatica', 'admin.local', 'ACTIVO', 'Seed de prueba', TRUE);

INSERT INTO bienes_patrimoniales (id, numero_patrimonial, categoria, descripcion, ubicacion, fuero, custodio, estado, equipo_id, observaciones, activo)
VALUES (1, 'PAT-SEED-001', 'PC', 'PC patrimonial seed', 'Informatica', 'Informatica', 'admin.local', 'EN_USO', 1, 'Seed de prueba', TRUE);

INSERT INTO actas (id, numero, tipo, equipo_id, fecha_emision, destinatario, responsable_entrega, responsable_recepcion, detalle, estado, observaciones, activo)
VALUES (1, 'ACT-SEED-001', 'ENTREGA', 1, DATE '2026-09-01', 'Mesa de Entradas', 'admin.local', 'mesa.entrada', 'Entrega inicial de equipo seed.', 'EMITIDA', 'Seed de prueba', TRUE);

INSERT INTO ubicaciones (id, codigo, nombre, tipo, fuero, responsable, edificio, piso, estado, observaciones, activo)
VALUES (1, 'UBI-SEED-001', 'Oficina Informatica', 'OFICINA', 'Informatica', 'admin.local', 'Centro Judicial San Pedro', 'PB', 'ACTIVA', 'Seed de prueba', TRUE);
