plugins { id 'com.android.application' }

android {
    namespace 'ar.gov.justiciajujuy.tareaslan'
    compileSdk 35
    defaultConfig {
        applicationId 'ar.gov.justiciajujuy.tareaslan'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        manifestPlaceholders = [cleartext: 'false']
    }
    buildTypes {
        debug {
            applicationIdSuffix '.piloto'
            versionNameSuffix '-piloto'
            manifestPlaceholders = [cleartext: 'true']
        }
        release { minifyEnabled false }
    }
    buildFeatures { buildConfig true }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
